// --- BASE DE DATOS DE ANIMES ---
// En un proyecto real, esto vendría de un servidor o una API.

export const animeData = [
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f2d6d93f5ba4a24bcb3b0d1322a645ff.jpg",
    heroImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=94,width=1920/CurationAssets/Solo%20Leveling/SEASON%202/ULTRA-WIDE/SoloLeveling-S2-KV1-UW-LTR.png",
    logoImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480/keyart/GDKHZEJ0K-title_logo-en-us",
    trailerUrl: "https://www.youtube.com/embed/TceDFwPXCuI?si=Pwe8qBK_wKzIZ6a7",
    description:
      "Conocido como el cazador más débil de la humanidad, se encuentra en una lucha constante por la supervivencia. Después de una experiencia cercana a la muerte, adquiere un poder único para subir de nivel.",
    genres: ["Acción", "Aventura", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodesTotal: 25,
    status: "Finalizado",
    year: 2024,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 122)), // Hace 122 dias
    episodes: [
      {
        season: 1,
        number: 1,
        title: "Estoy acostumbrado",
        duration: "23 min",
        description:
          "A Jin-Woo Sung lo conocen el cazador más débil de la humanidad, lo que lo convierte en objeto de burla de sus compañeros, aunque Ju-Hee Lee, una joven sanadora, siempre se preocupa por él y le ayuda a hacer amigos.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/9685e02cab2b3d22296e7c7e46d78aa8.jpe",
        releaseDate: "Enero 6, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "Si tuviera una oportunidad más",
        duration: "23 min",
        description:
          "Jin-Woo y sus compañeros están atrapados y no pueden hacer nada mientras la estatua de piedra los masacra uno a uno. Parece que hay una salida a este pérfido juego, pero ¿a qué precio?",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/50a0eb40c919b8efea01fd4799df08ff.jpe",
        releaseDate: "Enero 13, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "Es como un videojuego",
        duration: "24 min",
        description:
          "Para su sorpresa, Jin-Woo se despierta sano y salvo en el hospital. Al principio cree que los horripilantes sucesos que ha vivido son un sueño, pero las pantallas de estado no desaparecen y no parecen ser visibles para nadie más.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/c6adceca173ff32ae979af193a476fb2.jpe",
        releaseDate: "Enero 20, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "Tengo que hacerme más fuerte",
        duration: "24 min",
        description:
          "En un mundo donde portales misteriosos conectan con mazmorras llenas de monstruos, Sung Jin-Woo lucha por sobrevivir como el cazador más débil.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/78de61960488c9f16f960dae0b554eca.jpe",
        releaseDate: "Enero 27, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Un muy buen trato",
        duration: "24 min",
        description:
          "Cuando Jinwoo sale del hospital, las enfermeras se fijan en su buen estado físico. ¿Siempre tuvo tan buen cuerpo? Poco después, un grupo de Cazadores de rango C buscan un par de compañeros para rellenar y poder entrar a una mazmorra también C, así que como le ofrecen una buena cantidad, acepta.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/403416c5837765866f3b19ac27932777.jpe",
        releaseDate: "Febrero 3, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "Comienza la verdadera caza",
        duration: "24 min",
        description:
          "Jinwoo cae en la trampa que su nuevo equipo temporal le tiende y tiene que sobrevivir como puede, una vez más, ante un monstruo mucho más poderoso que él. A su lado está Jinho, a quien también han abandonado.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/4622fd0dd6f0072211526a8ae67f0c5c.jpe",
        releaseDate: "Febrero 10, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7,
        title: "Veamos hasta dónde puedo llegar",
        duration: "24 min",
        description:
          "Tras el incidente en la mazmorra de rango C, Jinwoo sigue con su vida como siempre, aunque su hermana no acaba de creer la gran evolución de su hermano.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/018425874ef4c1b18b32c26645d6c848.jpe",
        releaseDate: "Febrero 17, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7.5,
        title: "Episodio especial",
        duration: "24 min",
        description: "Repasamos la historia hasta el momento.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/693c3c2259bf67d2afd151453ff15e1d.jpe",
        releaseDate: "Febrero 24, 2024",
        language: "Subtitulado",
        videoUrl: "frame/Solo-Leveling/T1/1.html.html",
      },
      {
        season: 1,
        number: 8,
        title: "Esto es frustrante",
        duration: "24 min",
        description:
          "Tras su última incursión en una mazmorra, Jinwoo se ha dado cuenta de su propia debilidad. Quiere subir de nivel lo antes posible, pero eso podrá hacerlo si consigue entrar en las mazmorras.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/ba4454c313d44737a3a72fc390bd2159.jpe",
        releaseDate: "Marzo 2, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 9,
        title: "Has estado ocultando tus habilidades",
        duration: "24 min",
        description:
          "El grupo de supervivientes de la mazmorra doble entra en la mazmorra junto a los presos condenados y Kang Taeshik, el cazador encargado de supervisar a los prisioneros. Sin embargo, lo que parecía un viaje normal a una mazmorra acaba siendo un río de sangre.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/08ade842ca3ae544ccc5e4f6a207b529.jpe",
        releaseDate: "Marzo 9, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 10,
        title: "¿Qué es esto, un pícnic?",
        duration: "24 min",
        description:
          "Jinwoo y Jinho preparan un grupo repleto de figurantes para entrar ellos solos a las mazmorras y conseguir dinero, pero esto hace que Tigre Blanco se fije en las posibles capacidades de Jinwoo y sospechen de que vivió un segundo despertar.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/9833d2909af5311139e79b32a44d9605.jpe",
        releaseDate: "Marzo 16, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 11,
        title: "Un caballero defendiendo un trono vacío",
        duration: "24 min",
        description:
          "Sung Jinwoo inicia la misión para cambiar de clase y se enfrenta a un enemigo formidable. Mientras, Jinho se reúne con su familia y otros cazadores visitan la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/66e3cabc8e0557f77c93c24178e7a5cd.jpe",
        releaseDate: "Marzo 23, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 12,
        title: "Surge",
        duration: "24 min",
        description:
          "Mientras Jinwoo se enfrenta a sí mismo e intenta completar el cambio de clase, Choi Jong-in y los cazadores que lo acompañan descubren algo en la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,fit=contain,width=320,height=180,quality=70/catalog/crunchyroll/cda77a98de7021522ebb5f0cc9bebd7d.jpe",
        releaseDate: "Marzo 30, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      // Temporada 2 (Arise from the Shadow) - Las fechas son especulativas basadas en el archivo
      {
        season: 2,
        number: 13,
        title: "Tú no eres nivel E, ¿verdad?.",
        duration: "23m",
        description:
          "Comienza la segunda temporada. Jinwoo, ahora como Monarca de las Sombras, atrae la atención de poderosos gremios y figuras misteriosas. Su identidad ya no es un secreto.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/b27889eed12a1c5c1c5765eb0d8f82dc.jpg",
        releaseDate: "Enero 4, 2025",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/13.html",
      },
      {
        season: 2,
        number: 14,
        title: "Parece que tú mismo no lo sabes.",
        duration: "23m",
        description:
          "Jinwoo comienza a construir su propio gremio de sombras. Se encuentra con nuevos aliados y enemigos mientras explora los límites de sus recién adquiridos poderes de nigromante.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/e1a8566071311d4a6720540b0d02a623.jpg",
        releaseDate: "Enero 11, 2025",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/14.html",
      },
      {
        season: 2,
        number: 15,
        title: "Aún queda mucho camino.",
        duration: "23m",
        description:
          "Una puerta roja, la más peligrosa de todas, aparece. Jinwoo y su ejército de sombras son los únicos capaces de enfrentarse a la amenaza que yace en su interior.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/707acde43312c043b135a8d8d12f0372.jpg",
        releaseDate: "Enero 18, 2025",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/15.html",
      },
      {
        season: 2,
        number: 16,
        title: "Tengo que dejar de fingir.",
        duration: "23m",
        description:
          "La incursión en la puerta roja lleva a Jinwoo a una batalla contra una tribu de elfos de hielo. Añade a su comandante, Baruka, a su ejército de sombras.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/9b05cfa6ea5183e13a8456fed1908357.jpg",
        releaseDate: "Enero 25, 2025",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/16.html",
      },
      {
        season: 2,
        number: 17,
        title: "Estamos entrenados para esto.",
        duration: "23m",
        description:
          "Se celebra la Conferencia Internacional de Gremios en Estados Unidos. Jinwoo es invitado, pero los cazadores de todo el mundo no son los únicos interesados en él.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/1a46858f76a4b9cb80d60f59e69318b0.jpg",
        releaseDate: "01/02/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/17.html",
      },
      {
        season: 2,
        number: 18,
        title: "No menosprecies a los míos.",
        duration: "23m",
        description:
          "Durante la conferencia, un portal de rango S se abre inesperadamente en Japón. Jinwoo decide intervenir, mostrando al mundo el verdadero poder del Monarca de las Sombras.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/9ab321592ad21bb42b9c746e8057239a.jpg",
        releaseDate: "08/02/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/18.html",
      },
      {
        season: 2,
        number: 19,
        title: "El décimo Cazador de rango S.",
        duration: "23m",
        description:
          "Después de conquistar la mazmorra de rango S en Japón y derrotar al rey de los gigantes, Beru, Jinwoo se convierte oficialmente en el décimo cazador de rango S de Corea.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/ad0478978006763a1df8cd8b2cbf4f0d.jpg",
        releaseDate: "15/02/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/19.html",
      },
      {
        season: 2,
        number: 20,
        title: "Mirar hacia arriba me estaba cansando.",
        duration: "23m",
        description:
          "Los Monarcas, los verdaderos enemigos, comienzan a moverse. Jinwoo descubre la verdad sobre el Sistema y su papel en la guerra eterna entre los Monarcas y los Gobernantes.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/29945b927a6c4d2dc4cd23c3360e7d28.jpg",
        releaseDate: "22/02/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/20.html",
      },
      {
        season: 2,
        number: 21,
        title: "Valió la pena.",
        duration: "23m",
        description:
          "Jinwoo se enfrenta a los Monarcas de las Plagas, las Bestias y la Escarcha. Es una batalla desesperada en la que debe usar todo su poder para proteger a sus seres queridos.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/8be7a55bbacc671d73a2efa0531dfeba.jpg",
        releaseDate: "01/03/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/21.html",
      },
      {
        season: 2,
        number: 22,
        title: "Necesitamos un héroe.",
        duration: "23m",
        description:
          "El mundo está al borde de la destrucción. Jinwoo, ahora con el corazón negro y el poder completo del Monarca de las Sombras, se prepara para la batalla final contra Antares, el Rey de los Dragones.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/d909160a8e78313e1530ed881d57831d.jpg",
        releaseDate: "08/03/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/22.html",
      },
      {
        season: 2,
        number: 23,
        title: "Se va a poner aún más intenso.",
        duration: "23m",
        description:
          "La guerra contra los Monarcas llega a su punto culminante. Jinwoo y su ejército de 10 millones de sombras se enfrentan al ejército de destrucción de Antares.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/498a19937f80f45b460db38226731b2e.jpg",
        releaseDate: "15/03/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/23.html",
      },
      {
        season: 2,
        number: 24,
        title: "¿Eres el rey de los humanos?.",
        duration: "23m",
        description:
          "Después de una batalla épica, Jinwoo derrota a Antares. Con la guerra terminada, los Gobernantes le ofrecen una elección: vivir en el mundo restaurado o usar la Copa de la Reencarnación para retroceder en el tiempo.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/58a7fe907f22d3001e3afea92c7cb6a0.jpg",
        releaseDate: "22/03/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/24.html",
      },
      {
        season: 2,
        number: 25,
        title: "Al siguiente objetivo.",
        duration: "23m",
        description:
          "Jinwoo elige retroceder el tiempo y libra la guerra contra los Monarcas solo durante 27 años en una dimensión diferente. Regresa a un mundo en paz, donde solo él recuerda los eventos pasados, listo para vivir una vida normal.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/5f581a5a1659cd92fa40fe530206b7f4.jpg",
        releaseDate: "29/03/25",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T2/25.html",
      },
    ],
  },
  {
    id: "pokemon-horizons",
    title: "Pokémon: Horizons",
    img: "https://cdn.jkdesu.com/assets/images/animes/image/pokemon-shinsaku-anime.jpg",
    heroImg:
      "https://occ-0-1472-3933.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABZkn668wtTIk2Wj95lXRnBdbtWHwlbHANeTm90WzC9sODu264-K_UlZ48VH57ZWCtksRr8vryMNLFYm7I9nlRB2Cqbl2qo-dpJmq.jpg?r=f75",
    logoImg:
      "https://upload.wikimedia.org/wikipedia/commons/e/e8/Pok%C3%A9mon_Horizons_The_Series_Logo.png",
    trailerUrl: "https://www.youtube.com/embed/_c_hMehCORQ",
    description:
      "Pocket Mosnters, Pokemon para abreviar. Las extrañas y misteriosas criaturas de este planeta se pueden ver en todas partes: en el cielo, en el mar, en el bosque y en la ciudad. Liko, una chica de Pardea con un misterioso colgante, y Roy, un chico de Kantou que sostiene una misteriosa bola monstruosa. Ambientada en el vasto mundo de Pokemon. ¡Comienzan las nuevas aventuras de Liko y Roy! ¿Qué encuentros les esperan y qué destino les aguarda? Esta es una historia sobre “encontrar” algo importante a través de la aventura.",
    genres: ["Acción", "Comedia", "Aventura", "Fantasía", "Infantil"],
    rating: 4.7,
    seasons: 1,
    episodesTotal: 99,
    status: "En Emisión",
    year: 2023,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 8)), // Hace 8 dias
    episodes: [
      {
        season: 1,
        number: 1,
        title: "del principio.",
        duration: "24m",
        description:
          "Liko, de la región de Paldea, llega a la Academia Índigo en Kanto, donde recibe a su primer compañero Pokémon, Sprigatito. Sin embargo, un grupo misterioso aparece buscando su enigmático colgante.",
        img: "image/Pokemon-Horizons/1.jpg",
        releaseDate: "14/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "del principio, parte 2.",
        duration: "24m",
        description:
          "Liko es rescatada por los Tacleadas de Voltios, un grupo de aventureros. Friede y su Charizard se enfrentan a los Exploradores para proteger a Liko y su colgante.",
        img: "image/Pokemon-Horizons/2.jpg",
        releaseDate: "14/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "con Sprigatito.",
        duration: "24m",
        description:
          "A bordo de la aeronave de los Tacleadas de Voltios, Sprigatito desaparece. Liko, con la ayuda de su nuevo amigo Roy, debe encontrar a su compañero antes de que los Exploradores ataquen de nuevo.",
        img: "image/Pokemon-Horizons/3.jpg",
        releaseDate: "21/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "arrastrado por la marea.",
        duration: "24m",
        description:
          "Roy le muestra a Liko su base secreta. Mientras tanto, los Tacleadas de Voltios buscan a un Pokémon raro, Fuecoco, que ha sido visto en la isla. Roy sueña con convertirse en un Entrenador Pokémon.",
        img: "image/Pokemon-Horizons/4.jpg",
        releaseDate: "28/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Te  Fuecoco.",
        duration: "24m",
        description:
          "Fuecoco, atraído por el canto, se une a Roy. Juntos, se enfrentan a los Exploradores, y Roy demuestra su valentía como nuevo Entrenador Pokémon.",
        img: "image/Pokemon-Horizons/5.jpg",
        releaseDate: "05/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "antigua.",
        duration: "24m",
        description:
          "El colgante de Liko revela un Pokémon misterioso que los protege. Siguiendo el consejo de la abuela de Liko, el grupo se dirige a Paldea para desentrañar el misterio de la Poké Ball antigua de Roy.",
        img: "image/Pokemon-Horizons/6.jpg",
        releaseDate: "12/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/6.html",
      },
      {
        season: 1,
        number: 7,
        title: "¡Entrenamiento  Capitán Pikachu.",
        duration: "24m",
        description:
          "Liko y Roy comienzan su entrenamiento especial con el Capitán Pikachu para fortalecer sus lazos con Sprigatito y Fuecoco y mejorar sus habilidades de combate.",
        img: "image/Pokemon-Horizons/7.jpg",
        releaseDate: "19/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/7.html",
      },
      {
        season: 1,
        number: 8,
        title: "de la puerta que no se abre.",
        duration: "24m",
        description:
          "La aeronave necesita reparaciones, y el grupo se detiene. Descubren una puerta misteriosa que no se abre, y Dot, la experta en tecnología del grupo, intenta resolver el enigma.",
        img: "image/Pokemon-Horizons/8.jpg",
        releaseDate: "26/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/8.html",
      },
      {
        season: 1,
        number: 9,
        title: "Paldea!.",
        duration: "24m",
        description:
          "Los Tacleadas de Voltios finalmente llegan a la región de Paldea. Liko está emocionada por regresar a casa, pero los peligros de los Exploradores aún los acechan.",
        img: "image/Pokemon-Horizons/9.jpg",
        releaseDate: "02/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/9.html",
      },
      {
        season: 1,
        number: 10,
        title: "Brassius.",
        duration: "24m",
        description:
          "En su búsqueda de información, Liko y Roy conocen a Nemona, una entrenadora de alto rango, y a Brassius, el líder de gimnasio de tipo Planta, quien parece tener una conexión con el Rayquaza negro.",
        img: "image/Pokemon-Horizons/10.jpg",
        releaseDate: "09/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/10.html",
      },
      {
        season: 1,
        number: 11,
        title: "El Bosque de Arboliva.",
        duration: "24m",
        description:
          "El grupo se adentra en el Bosque de Arboliva, donde se encuentran con un Arboliva gigante, uno de los seis héroes del antiguo aventurero Lucius, que parece estar herido.",
        img: "image/Pokemon-Horizons/11.jpg",
        releaseDate: "16/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/11.html",
      },
      {
        season: 1,
        number: 12,
        title: "El futuro que elijo.",
        duration: "24m",
        description:
          "Con el bosque en llamas, Liko y Sprigatito deben superar sus miedos para salvar al Arboliva gigante. El colgante de Liko vuelve a brillar, revelando su verdadero poder.",
        img: "image/Pokemon-Horizons/12.jpg",
        releaseDate: "23/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/12.html",
      },
      {
        season: 1,
        number: 13,
        title: "Un picnic repentino.",
        duration: "24m",
        description:
          "Después de la intensa batalla, el grupo decide tomar un descanso y hacer un picnic. Es un momento de calma para conocerse mejor y fortalecer sus lazos.",
        img: "https://image.tmdb.org/t/p/w300/aexpQXTfIcienaPGC4elDfFiTe8.jpg",
        releaseDate: "14/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/13.html",
      },
      {
        season: 1,
        number: 14,
        title: "¡Vuela! ¡¡Wattrel!!.",
        duration: "24m",
        description:
          "Un Wattrel que no puede volar le recuerda a Roy su propio pasado. Él y Fuecoco deciden ayudar al pequeño Pokémon a surcar los cielos.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-14.jpg",
        releaseDate: "21/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/14.html",
      },
      {
        season: 1,
        number: 15,
        title: "¡Alguien a quién no podemos ver! ¿Quién podrá ser?.",
        duration: "24m",
        description:
          "Algo o alguien invisible está causando travesuras en la aeronave. Dot y su Quaxly intentan descubrir al misterioso culpable.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-15.jpg",
        releaseDate: "28/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/15.html",
      },
      {
        season: 1,
        number: 16,
        title: "Mientras esté con Quaxly.",
        duration: "24m",
        description:
          "Se revela que el Pokémon invisible es un Polteageist. Liko ayuda a Dot a comprender mejor los sentimientos de su Quaxly para resolver el problema.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-16.jpg",
        releaseDate: "04/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/16.html",
      },
      {
        season: 1,
        number: 17,
        title: "¡Wattrel y Fuecoco: Entrenamiento secreto!.",
        duration: "24m",
        description:
          "Roy idea un entrenamiento secreto para que Wattrel y Fuecoco aprendan un nuevo movimiento combinado para impresionar a Friede.",
        img: "https://image.tmdb.org/t/p/w300/mbwNHNdQOBtaPfvocQOAvstNuxP.jpg",
        releaseDate: "11/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/17.html",
      },
      {
        season: 1,
        number: 18,
        title: "¡Vuela alto Pikachu, el cielo es el límite!.",
        duration: "24m",
        description:
          "El Capitán Pikachu muestra sus impresionantes habilidades de vuelo, inspirando a todo el equipo de los Tacleadas de Voltios.",
        img: "https://image.tmdb.org/t/p/w300/bK6nhaoHxuuqvp0TryDzyqswEVw.jpg",
        releaseDate: "18/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/18.html",
      },
      {
        season: 1,
        number: 19,
        title: "La verdad sobre Alcremie.",
        duration: "24m",
        description:
          "Murdock, el cocinero de la aeronave, está de mal humor. Liko y Roy investigan y descubren que el problema está relacionado con su Alcremie.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-19.webp",
        releaseDate: "25/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/19.html",
      },
      {
        season: 1,
        number: 20,
        title: "Batalla de entrenamiento con Kabu-san.",
        duration: "24m",
        description:
          "El grupo llega a la región de Galar y se encuentra con Kabu, el líder de gimnasio de tipo Fuego. Liko y Roy tienen una batalla de entrenamiento para probar su valía.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-20.jpg",
        releaseDate: "01/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/20.html",
      },
      {
        season: 1,
        number: 21,
        title: "¡La Hatenna que está sola!.",
        duration: "24m",
        description:
          "Liko encuentra una Hatenna solitaria que evita a las personas. Ella intenta ganarse la confianza del tímido Pokémon.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-21.webp",
        releaseDate: "08/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/21.html",
      },
      {
        season: 1,
        number: 22,
        title: "¡Choque en las minas de Galar!.",
        duration: "24m",
        description:
          "En las minas de Galar, los Tacleadas de Voltios se enfrentan nuevamente a los Exploradores, esta vez liderados por el astuto Spinel.",
        img: "https://image.tmdb.org/t/p/w300/mnVtj7XFhOLaGedViQNnQWjV1BK.jpg",
        releaseDate: "15/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/22.html",
      },
      {
        season: 1,
        number: 23,
        title: "¡El ardiente Moltres de Galar!.",
        duration: "24m",
        description:
          "Dentro de la mina, el grupo se encuentra con el legendario Moltres de Galar, otro de los seis héroes de Lucius, que está bajo un extraño control.",
        img: "https://image.tmdb.org/t/p/w300/aSqhLx2HlNDJ9oZuMyPddhAr0m3.jpg",
        releaseDate: "22/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/23.html",
      },
      {
        season: 1,
        number: 24,
        title: "Reunión en el antiguo castillo.",
        duration: "24m",
        description:
          "Siguiendo el rastro de la Poké Ball antigua, Liko visita a su abuela en un viejo castillo, donde se reencuentra con Diana y descubre más sobre Lucius.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-24.webp",
        releaseDate: "14/10/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/24.html",
      },
      {
        season: 1,
        number: 25,
        title: "¡Rivales en la noche oscura!.",
        duration: "24m",
        description:
          "Spinel de los Exploradores tiende una emboscada en el castillo. Liko y Roy deben proteger el colgante y enfrentarse a él y a su poderoso Umbreon.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-25.webp",
        releaseDate: "20/10/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/25.html",
      },
      {
        season: 1,
        number: 26,
        title: "La aventura de Terapagos.",
        duration: "24m",
        description:
          "El colgante finalmente se abre, revelando a un misterioso Pokémon tortuga. Diana lo identifica como Terapagos, comenzando una nueva etapa en la aventura.",
        img: "https://image.tmdb.org/t/p/w300/6YL02AlYxilPk8zfYk6lMk5sgp7.jpg",
        releaseDate: "07/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/26.html",
      },
      {
        season: 1,
        number: 27,
        title: "Mientras esté con mis amigos.",
        duration: "24m",
        description:
          "El grupo necesita reparar la aeronave. Para conseguir fondos, Liko, Roy y Dot deciden ayudar a un comerciante local con sus tareas.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-27.webp",
        releaseDate: "07/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/27.html",
      },
      {
        season: 1,
        number: 28,
        title: "Mientras esté con mis amigos.",
        duration: "24m",
        description:
          "La segunda parte del episodio 27. Liko, Roy y Dot continúan sus trabajos para ayudar a reparar el Valiente Asagi, fortaleciendo su amistad en el proceso.",
        img: "https://image.tmdb.org/t/p/w300/5jDep84tch9dmuHDwh8ImiM3Xsj.jpg",
        releaseDate: "11/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/28.html",
      },
      {
        season: 1,
        number: 29,
        title: "Orio y la artesana de Monster Ball.",
        duration: "24m",
        description:
          "Orio, la mecánica, visita a una artesana de Poké Balls para conseguir materiales. Liko y Roy la acompañan y aprenden sobre el antiguo arte de la fabricación de Poké Balls.",
        img: "https://image.tmdb.org/t/p/w300/5IO1vxBkf9VlZg7gPShjNhgZ9yn.jpg",
        releaseDate: "18/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/29.html",
      },
      {
        season: 1,
        number: 30,
        title: "¡¿El Pokémon misterioso que sorbe y aplasta?!.",
        duration: "24m",
        description:
          "Un Pokémon desconocido está causando problemas en la cocina al sorber la electricidad. El grupo debe identificar y detener a la criatura escurridiza.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-30.webp",
        releaseDate: "25/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/30.html",
      },
      {
        season: 1,
        number: 31,
        title: "La canción en la niebla.",
        duration: "24m",
        description:
          "Una espesa niebla rodea la aeronave y se escucha una canción misteriosa. La leyenda dice que es un Lapras, otro de los seis héroes de Lucius.",
        img: "https://image.tmdb.org/t/p/w300/daSHMLMsQ6lIwvGH8PPKXAhBywL.jpg",
        releaseDate: "02/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/31.html",
      },
      {
        season: 1,
        number: 32,
        title: "¡Los sentimientos de Lapras por sus amigos!.",
        duration: "24m",
        description:
          "El grupo descubre que el Lapras de Lucius protege a otros Pokémon heridos. Liko y Roy deben ganarse su confianza para poder ayudar.",
        img: "https://image.tmdb.org/t/p/w300/5dF3dIUsyenLPSyf1Qh50Ql3Z4A.jpg",
        releaseDate: "09/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/32.html",
      },
      {
        season: 1,
        number: 33,
        title: "El rugiente Rayquaza negro.",
        duration: "24m",
        description:
          "El legendario Rayquaza negro aparece. Amethio de los Exploradores también llega para desafiarlo, resultando en una batalla colosal que pone a todos en peligro.",
        img: "https://image.tmdb.org/t/p/w300/gn3PBYUbapyyObeOPfT745M8RQd.jpg",
        releaseDate: "16/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/33.html",
      },
      {
        season: 1,
        number: 34,
        title: "¡Cada quien por su camino!.",
        duration: "24m",
        description:
          "Tras la batalla con Rayquaza, el grupo se separa para entrenar individualmente y volverse más fuertes, prometiendo reunirse en el futuro.",
        img: "https://image.tmdb.org/t/p/w300/z9Yk1iym7SWeyJdE0zFOITQTTZH.jpg",
        releaseDate: "23/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/34.html",
      },
      {
        season: 1,
        number: 35,
        title: "Un dúo en el desierto: Friede y Cap.",
        duration: "24m",
        description:
          "Friede y el Capitán Pikachu se encuentran con una antigua rival en el desierto. Un flashback revela cómo se conocieron y formaron su fuerte vínculo.",
        img: "image/Pokemon-Horizons/35.jpg",
        releaseDate: "13/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/35.html",
      },
      {
        season: 1,
        number: 36,
        title: "Operación ¡Amistad Oinkologne!.",
        duration: "24m",
        description:
          "Roy intenta ayudar a un par de Oinkologne rivales a hacerse amigos, organizando una operación especial para que trabajen juntos.",
        img: "https://image.tmdb.org/t/p/w300/ks24qtUi9ncZxMOuHyKmWqoXO9r.jpg",
        releaseDate: "20/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/36.html",
      },
      {
        season: 1,
        number: 37,
        title: "¿Fuecoco se convierte en un chico malo?.",
        duration: "24m",
        description:
          "Fuecoco comienza a actuar de forma rebelde y desobediente. Roy debe entender qué le sucede a su amigo para recuperar su confianza.",
        img: "https://image.tmdb.org/t/p/w300/lyavl8OW1TSaaDdDjZKN4KkG4S2.jpg",
        releaseDate: "27/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/37.html",
      },
      {
        season: 1,
        number: 38,
        title: "¿Un SOS de Tandemaus?.",
        duration: "24m",
        description:
          "Liko y su Hatenna reciben una señal de socorro de un Tandemaus. Deben encontrar la fuente del problema y ayudar al pequeño Pokémon ratón.",
        img: "https://image.tmdb.org/t/p/w300/dTrFyERs2BVKN91Gnd9QuMZhpm4.jpg",
        releaseDate: "03/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/38.html",
      },
      {
        season: 1,
        number: 39,
        title: "¡Tinkatink y el martillo de sus obsesiones!.",
        duration: "24m",
        description:
          "Un Tinkatink está robando objetos metálicos para construir su martillo. Dot y su Quaxly intentan detenerlo y enseñarle una lección.",
        img: "https://image.tmdb.org/t/p/w300/ulElHyjCDbdMojmrH22XCrP1ylP.jpg",
        releaseDate: "10/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/39.html",
      },
      {
        season: 1,
        number: 40,
        title: "¿Adiós, Sprigatito?.",
        duration: "24m",
        description:
          "Liko se preocupa por el comportamiento distante de Sprigatito. Teme que su compañero quiera dejarla, y debe enfrentar sus inseguridades para fortalecer su vínculo.",
        img: "https://image.tmdb.org/t/p/w300/9f9fU2Bw6gGYaa2TMUWnDwPrrjv.jpg",
        releaseDate: "17/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/40.html",
      },
      {
        season: 1,
        number: 41,
        title: "¡Aparece la mamá intensa!.",
        duration: "24m",
        description:
          "La madre de Liko, Lucca, una influyente figura, visita la aeronave. Su presencia pone a Liko nerviosa, quien busca impresionar a su exigente madre.",
        img: "https://image.tmdb.org/t/p/w300/stzTiUQGXCEz2gdz8DbvpbWg40N.jpg",
        releaseDate: "02/03/24",
      },
      {
        season: 1,
        number: 42,
        title: "El futuro que elijo.",
        duration: "24m",
        description:
          "Una vez más, Liko se enfrenta a una decisión crucial sobre su futuro y el de sus amigos. Recordando sus aventuras, toma una resolución importante.",
        img: "https://image.tmdb.org/t/p/w300/6uQBd2GaMWiUO7SGgp0sHAf4La6.jpg",
        releaseDate: "09/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/42.html",
      },
      {
        season: 1,
        number: 43,
        title: "El desafio de los exploradores.",
        duration: "24m",
        description:
          "Los Exploradores lanzan un nuevo y audaz desafío a los Tacleadas de Voltios, con la intención de apoderarse de Terapagos de una vez por todas.",
        img: "https://image.tmdb.org/t/p/w300/8Ti8CEBFbYVDLpeazuzARcSobfe.jpg",
        releaseDate: "16/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/43.html",
      },
      {
        season: 1,
        number: 44,
        title: "¡El plan para capturar a Rayquaza!.",
        duration: "24m",
        description:
          "Los Exploradores revelan su elaborado plan para capturar al Rayquaza negro. Los Tacleadas de Voltios deben intervenir para proteger al Pokémon legendario.",
        img: "https://image.tmdb.org/t/p/w300/juuSqkbTpJIzUEGZvcown1Ghdbu.jpg",
        releaseDate: "23/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/44.html",
      },
      {
        season: 1,
        number: 45,
        title: "Muy, muy lejos.",
        duration: "24m",
        description:
          "La batalla final por Rayquaza y Terapagos alcanza su clímax. Liko y Roy deben usar todo lo que han aprendido para proteger a sus amigos y al mundo.",
        img: "https://image.tmdb.org/t/p/w300/5c6p8xmKfW2Tmt1Vgrp1d1Jyeoa.jpg",
        releaseDate: "30/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/45.html",
      },
      {
        season: 1,
        number: 46,
        title: "¡La emocionante Academia Naranja!.",
        duration: "24m",
        description:
          "Liko, Roy y Dot se inscriben en la Academia Naranja para un curso de entrenamiento especial sobre la Teracristalización, donde conocen nuevos amigos y rivales.",
        img: "https://image.tmdb.org/t/p/w300/hdy614vEE6EA5tIA9rtFgc47HAw.jpg",
        releaseDate: "13/04/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/46.html",
      },
      {
        season: 1,
        number: 47,
        title: "¡Liko y Floragato, con todo el corazón!.",
        duration: "24m",
        description:
          "Sprigatito evoluciona a Floragato. Liko debe aprender a sincronizarse con la nueva personalidad y estilo de lucha de su compañero.",
        img: "https://image.tmdb.org/t/p/w300/9yWglObQVD2iF4npwSCq6NRCjlK.jpg",
        releaseDate: "20/04/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/47.html",
      },
      {
        season: 1,
        number: 48,
        title: "¡Brilla! ¡El destello del fuego y el arte!.",
        duration: "24m",
        description:
          "Roy y Fuecoco tienen su primer desafío Teracristal contra Brassius. Deben combinar el arte y el poder del fuego para ganar.",
        img: "image/Pokemon-Horizons/48.jpg",
        releaseDate: "04/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/48.html",
      },
      {
        season: 1,
        number: 49,
        title: "Dot y Gurumin.",
        duration: "24m",
        description:
          "La identidad secreta de Dot como la streamer Gurumin está en riesgo cuando una fanática la desafía. Dot debe equilibrar su vida real y su alter ego.",
        img: "image/Pokemon-Horizons/49.jpg",
        releaseDate: "11/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/49.html",
      },
      {
        season: 1,
        number: 50,
        title: "¡Deslumbra, Teracristalización! ¡¡Baila, Baila, Quaxly!!.",
        duration: "24m",
        description:
          "Dot y Quaxly se enfrentan a un desafío de baile que requiere el poder de la Teracristalización. Quaxly evoluciona a Quaxwell.",
        img: "image/Pokemon-Horizons/50.jpg",
        releaseDate: "18/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/50.html",
      },
      {
        season: 1,
        number: 51,
        title: "¡¿Un Floragato espinoso?! El misterioso pilar de flores.",
        duration: "24m",
        description:
          "Floragato no puede controlar su nuevo poder, creando un pilar de espinas. Liko debe ayudarla a dominar su habilidad antes de que cause más problemas.",
        img: "image/Pokemon-Horizons/51.jpg",
        releaseDate: "25/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/51.html",
      },
      {
        season: 1,
        number: 52,
        title: "¡Wattrel, alerta de huracán!.",
        duration: "24m",
        description:
          "El Wattrel de Roy evoluciona a Kilowattrel y accidentalmente crea un pequeño huracán. Roy debe aprender a manejar el nuevo poder de su Pokémon.",
        img: "image/Pokemon-Horizons/52.jpg",
        releaseDate: "01/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/52.html",
      },
      {
        season: 1,
        number: 53,
        title: "Hatenna y el que no es de este mundo.",
        duration: "24m",
        description:
          "El grupo encuentra a un misterioso Pokémon que no parece de su mundo, y la Hatenna de Liko siente una conexión especial con él.",
        img: "image/Pokemon-Horizons/53.jpg",
        releaseDate: "08/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/53.html",
      },
      {
        season: 1,
        number: 54,
        title: "Bendición eterna.",
        duration: "24m",
        description:
          "Liko, Roy y Dot buscan un lugar legendario en Paldea que se dice que concede una bendición eterna, esperando que ayude a Terapagos.",
        img: "image/Pokemon-Horizons/54.jpg",
        releaseDate: "15/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/54.html",
      },
      {
        season: 1,
        number: 55,
        title: "¡Enfrentamiento! La Élite Cuatro de Paldea.",
        duration: "24m",
        description:
          "Liko y Roy tienen la oportunidad de luchar contra miembros de la Élite Cuatro de Paldea, poniendo a prueba sus nuevas habilidades Teracristal.",
        img: "image/Pokemon-Horizons/55.jpg",
        releaseDate: "22/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/55.html",
      },
      {
        season: 1,
        number: 56,
        title: "¡Liko VS Chili! Más allá de la batalla.",
        duration: "24m",
        description:
          "Liko se enfrenta a Chili, miembro de la Élite Cuatro. La batalla le enseña una valiosa lección que va más allá de ganar o perder.",
        img: "image/Pokemon-Horizons/56.jpg",
        releaseDate: "29/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/56.html",
      },
      {
        season: 1,
        number: 57,
        title: "Un Terapagos que no conocía.",
        duration: "24m",
        description:
          "Terapagos revela una nueva forma y habilidad desconocida, sorprendiendo a todos y atrayendo la atención no deseada de los Exploradores.",
        img: "image/Pokemon-Horizons/57.jpg",
        releaseDate: "06/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/57.html",
      },
      {
        season: 1,
        number: 58,
        title: "¡¿El Pokémon mascota es Kingambit?!.",
        duration: "24m",
        description:
          "El grupo se encuentra con un Kingambit que actúa como el jefe de una banda de Pawniard y Bisharp. Deben demostrar su fuerza para ganarse su respeto.",
        img: "image/Pokemon-Horizons/58.jpg",
        releaseDate: "13/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/58.html",
      },
      {
        season: 1,
        number: 59,
        title: "¡Baila, Quaxly! ¡¡El paso azul de Champuru!!.",
        duration: "24m",
        description:
          "Quaxwell evoluciona a Quaquaval y debe perfeccionar su paso de baile característico para dominar su movimiento 'Danza Acuática'.",
        img: "image/Pokemon-Horizons/59.jpg",
        releaseDate: "27/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/59.html",
      },
      {
        season: 1,
        number: 60,
        title: "¡Nuestra primera nevada! ¡Ho-ho-ge!!.",
        duration: "24m",
        description:
          "El grupo experimenta su primera nevada en el Monte Nappe. Fuecoco, un Pokémon de fuego, no está acostumbrado al frío y Roy debe encontrar una manera de mantenerlo caliente.",
        img: "image/Pokemon-Horizons/60.jpg",
        releaseDate: "10/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/60.html",
      },
      {
        season: 1,
        number: 61,
        title: "¡Resuena, alma mía! ¡El desafío de Rhyme!.",
        duration: "24m",
        description:
          "Liko se enfrenta a Rhyme, la líder de gimnasio de tipo Fantasma, en una batalla doble que también es una actuación de rap.",
        img: "image/Pokemon-Horizons/61.jpg",
        releaseDate: "17/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/61.html",
      },
      {
        season: 1,
        number: 62,
        title: "¡La canción de Fuecoco y yo!.",
        duration: "24m",
        description:
          "Fuecoco evoluciona a Crocalor y obtiene un nido de fuego en su cabeza. Roy debe aprender a cantar en sintonía con él para potenciar su movimiento 'Canto Ardiente'.",
        img: "image/Pokemon-Horizons/62.jpg",
        releaseDate: "24/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/62.html",
      },
      {
        season: 1,
        number: 63,
        title: "¡La batalla de hielo! ¡Grusha de los ojos fríos!.",
        duration: "24m",
        description:
          "Roy desafía a Grusha, el líder de gimnasio de tipo Hielo. Debe usar el calor de Crocalor y su ingenio para derretir la fría estrategia de Grusha.",
        img: "image/Pokemon-Horizons/63.jpg",
        releaseDate: "31/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/63.html",
      },
      {
        season: 1,
        number: 64,
        title: "El monte Nappe y las sombras sigilosas.",
        duration: "24m",
        description:
          "Mientras entrenan en el Monte Nappe, unas misteriosas sombras comienzan a acechar al grupo. Deben descubrir qué son y cuáles son sus intenciones.",
        img: "image/Pokemon-Horizons/64.jpg",
        releaseDate: "07/09/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/64.html",
      },
      {
        season: 1,
        number: 65,
        title: "¡Liko y Amenthio!.",
        duration: "24m",
        description:
          "Liko tiene un encuentro inesperado con Amethio de los Exploradores. Esta vez, sin una batalla inminente, tienen una conversación que podría cambiar su rivalidad.",
        img: "image/Pokemon-Horizons/65.jpg",
        releaseDate: "14/09/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/65.html",
      },
      {
        season: 1,
        number: 66,
        title: "¡Ruptura del sistema! ¡¡Crisis en la Academia Naranja!!.",
        duration: "24m",
        description:
          "Un virus informático ataca el sistema de la Academia Naranja. Dot, junto con Penny, debe usar sus habilidades de hacking para detener la crisis.",
        img: "image/Pokemon-Horizons/66.jpg",
        releaseDate: "21/09/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/66.html",
      },
      {
        season: 1,
        number: 67,
        title: "¡¡Brilla, Teracristalización!! ¡Liko VS Roy!.",
        duration: "24m",
        description:
          "Como parte de su examen final en la academia, Liko y Roy se enfrentan en una batalla Teracristal para demostrar todo lo que han aprendido.",
        img: "image/Pokemon-Horizons/67.jpg",
        releaseDate: "28/09/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/67.html",
      },
      {
        season: 1,
        number: 68,
        title: "¡Hacia un Nuevo Cielo! ¡¡El Valiente Asagi!!.",
        duration: "24m",
        description:
          "Con su entrenamiento en Paldea completo, los Tacleadas de Voltios se preparan para una nueva aventura, zarpando en el Valiente Asagi hacia un destino desconocido.",
        img: "image/Pokemon-Horizons/68.jpg",
        releaseDate: "12/10/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/68.html",
      },
      {
        season: 1,
        number: 69,
        title: "¡¿Yo soy un Pokémon y tú eres yo?!.",
        duration: "24m",
        description:
          "Un extraño fenómeno causa que Liko y Sprigatito intercambien cuerpos. Deben aprender a vivir en el cuerpo del otro mientras buscan una solución.",
        img: "image/Pokemon-Horizons/69.jpg",
        releaseDate: "19/10/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/69.html",
      },
      {
        season: 1,
        number: 70,
        title: "¡El martillo de Tinkatink no se construyó en un día!.",
        duration: "24m",
        description:
          "El grupo se encuentra de nuevo con el Tinkatink, que ahora lidera a su clan. Dot se inspira en su perseverancia y trabajo duro.",
        img: "https://image.tmdb.org/t/p/w300/fpF9oWhAYC38yjcQ4rIvFMszJrM.jpg",
        releaseDate: "26/10/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/70.html",
      },
      {
        season: 1,
        number: 71,
        title: "Encuentro en el Lago Cristalino.",
        duration: "24m",
        description:
          "Terapagos guía al grupo a un lago cristalino donde se encuentran con un Pokémon legendario que parece tener una conexión con Lucius.",
        img: "https://image.tmdb.org/t/p/w300/d1RfarxY2lxEqX8gwADZqg6fNkr.jpg",
        releaseDate: "02/11/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/71.html",
      },
      {
        season: 1,
        number: 72,
        title: "¡Persecución! ¡¡Encuentren a Kleavor!!.",
        duration: "24m",
        description:
          "Un Kleavor, otro de los Pokémon de Lucius, está causando estragos. Roy, inspirado por las leyendas, se propone calmar al Pokémon hacha.",
        img: "image/Pokemon-Horizons/72.jpg",
        releaseDate: "09/11/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/72.html",
      },
      {
        season: 1,
        number: 73,
        title: "Kleavor, el guerrero solitario.",
        duration: "24m",
        description:
          "Roy logra conectar con Kleavor, entendiendo su soledad y su deseo de probar su fuerza. Se gana el respeto del Pokémon y una nueva pista sobre Lucius.",
        img: "image/Pokemon-Horizons/73.jpg",
        releaseDate: "16/11/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/73.html",
      },
      {
        season: 1,
        number: 74,
        title: "Los tres Exploradores.",
        duration: "24m",
        description:
          "Se revela más sobre los administradores de los Exploradores. Coral, Sidian y Chalce muestran sus personalidades y sus poderosos Pokémon en una misión.",
        img: "image/Pokemon-Horizons/74.jpg",
        releaseDate: "23/11/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/74.html",
      },
      {
        season: 1,
        number: 75,
        title: "El futuro que se nos ha confiado, el brillo de este mundo.",
        duration: "24m",
        description:
          "Reflexionando sobre su viaje, Liko y Roy comprenden la gran responsabilidad que tienen para proteger a Terapagos y descubrir los secretos de Lucius.",
        img: "https://image.tmdb.org/t/p/w300/qU9MzSOKQDDEfLYu1ES0wpH72EA.jpg",
        releaseDate: "30/11/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/75.html",
      },
      {
        season: 1,
        number: 76,
        title: "¿Sonano? ¡Sodayo!.",
        duration: "24m",
        description:
          "El grupo se encuentra con un Wobbuffet y un Wynaut que siempre parecen estar de acuerdo. Su dinámica enseña a Liko y Roy sobre la comunicación y el trabajo en equipo.",
        img: "image/Pokemon-Horizons/76.jpg",
        releaseDate: "07/12/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/76.html",
      },
      {
        season: 1,
        number: 77,
        title: "Randou regresa a su ciudad natal.",
        duration: "24m",
        description:
          "Landau, el pescador y miembro de los Tacleadas de Voltios, regresa a su hogar, donde el grupo aprende más sobre su pasado y su familia.",
        img: "https://image.tmdb.org/t/p/w300/6W6vnq3MP4gQIWpXKnhajzFj3cU.jpg",
        releaseDate: "14/12/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/77.html",
      },
      {
        season: 1,
        number: 78,
        title: "¡Feroz batalla con Entei! ¡¡Rugido de Fuego!!.",
        duration: "24m",
        description:
          "El Entei de Lucius aparece, y su poder es abrumador. Roy y Crocalor deben desatar todo su poder de fuego para enfrentarse al Pokémon legendario.",
        img: "https://image.tmdb.org/t/p/w300/gF4m1k9K8dZ7A3rkneLxSSziGyA.jpg",
        releaseDate: "21/12/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/78.html",
      },
      {
        season: 1,
        number: 79,
        title: "Más allá de la cima.",
        duration: "24m",
        description:
          "Tras la batalla con Entei, Roy se da cuenta de que todavía hay un largo camino por recorrer para alcanzar su sueño de derrotar a Rayquaza.",
        img: "image/Pokemon-Horizons/79.jpg",
        releaseDate: "11/01/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/79.html",
      },
      {
        season: 1,
        number: 80,
        title: "¡¿Pokémon asombrosos en el Área Cero?!.",
        duration: "24m",
        description:
          "El grupo finalmente se aventura en el misterioso Área Cero, donde encuentran Pokémon del pasado y del futuro, y se acercan más al secreto de Terapagos.",
        img: "image/Pokemon-Horizons/80.jpg",
        releaseDate: "18/01/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/80.html",
      },
      {
        season: 1,
        number: 81,
        title: "¡Una gran batalla! ¡El fuego que arrasa la tierra!.",
        duration: "24m",
        description:
          "En el corazón del Área Cero, los Tacleadas de Voltios se enfrentan a un poderoso Pokémon Paradoja que amenaza con desestabilizar todo el lugar.",
        img: "image/Pokemon-Horizons/81.jpg",
        releaseDate: "25/01/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/81.html",
      },
      {
        season: 1,
        number: 82,
        title: "¡Al final de un arcoíris brillante!.",
        duration: "24m",
        description:
          "Una pista sobre el último de los seis héroes de Lucius lleva al grupo a un lugar donde se dice que el final de un arcoíris toca la tierra.",
        img: "https://image.tmdb.org/t/p/w300/lvHdjB7yEFzIFe9FSO7ixKss5U9.jpg",
        releaseDate: "01/02/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/82.html",
      },
      {
        season: 1,
        number: 83,
        title: "¿La verdad es revelada? ¡La determinación de Amethio!.",
        duration: "24m",
        description:
          "Amethio, siguiendo sus propias pistas, descubre una verdad impactante sobre los Exploradores y su misión, lo que lo lleva a tomar una decisión crucial.",
        img: "https://image.tmdb.org/t/p/w300/do0cpvRMGZkJiVpPrUKcCg48knG.jpg",
        releaseDate: "08/02/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/83.html",
      },
      {
        season: 1,
        number: 84,
        title: "¡El lugar donde el cielo y la tierra se encuentran!.",
        duration: "24m",
        description:
          "Terapagos finalmente revela la ubicación de Rakua, el paraíso soñado por Lucius. El grupo se prepara para el tramo final de su viaje.",
        img: "image/Pokemon-Horizons/84.jpg",
        releaseDate: "15/02/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/84.html",
      },
      {
        season: 1,
        number: 85,
        title: "¡Llegamos! ¡El paraíso, Rakua!.",
        duration: "24m",
        description:
          "Los Tacleadas de Voltios llegan a Rakua, un lugar maravilloso y misterioso. Sin embargo, los Exploradores no se quedan atrás.",
        img: "https://image.tmdb.org/t/p/w300/ukjIXhW8vOl53zGdKZUzdw5C4HL.jpg",
        releaseDate: "22/02/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/85.html",
      },
      {
        season: 1,
        number: 86,
        title: "¡Los Tacleada de Voltios en ascenso VS los Exploradores!.",
        duration: "24m",
        description:
          "La batalla final entre los Tacleadas de Voltios y los Exploradores por el destino de Terapagos y Rakua comienza.",
        img: "https://image.tmdb.org/t/p/w300/vUA4oDiMKVmdQ1fQ4E0uAqhFwwZ.jpg",
        releaseDate: "01/03/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/86.html",
      },
      {
        season: 1,
        number: 87,
        title: "La guía del Rayquaza negro.",
        duration: "24m",
        description:
          "El Rayquaza negro reaparece, pero esta vez no como un enemigo, sino como una guía que muestra el verdadero propósito de Terapagos.",
        img: "image/Pokemon-Horizons/87.jpg",
        releaseDate: "08/03/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/87.html",
      },
      {
        season: 1,
        number: 88,
        title: "El Zygarde Blanco que sacude la tierra.",
        duration: "24m",
        description:
          "El último de los seis héroes se revela: un majestuoso Zygarde de color blanco que ha estado protegiendo el equilibrio de la tierra.",
        img: "https://image.tmdb.org/t/p/w300/9MPNahmqX45yqtZiX2w1ufD6RPe.jpg",
        releaseDate: "15/03/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/88.html",
      },
      {
        season: 1,
        number: 89,
        title: "¡Más allá de la aventura!.",
        duration: "24m",
        description:
          "Con el misterio de Lucius resuelto, Liko y Roy miran hacia el futuro, listos para embarcarse en nuevas aventuras con sus amigos y Pokémon.",
        img: "https://image.tmdb.org/t/p/w300/7F6CvGQANnr521wVIMNHN1wkUOy.jpg",
        releaseDate: "22/03/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/89.html",
      },
      {
        season: 1,
        number: 90,
        title: "Hacia el gran cielo, de nuevo Parte 1.",
        duration: "24m",
        description:
          "Una nueva trama comienza cuando los Tacleadas de Voltios reciben una nueva misión que los llevará a una región inexplorada.",
        img: "https://image.tmdb.org/t/p/w300/luf4FhAZRs8GfwguAs7V41xUNiP.jpg",
        releaseDate: "12/04/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/90.html",
      },
      {
        season: 1,
        number: 91,
        title: "Hacia el gran cielo, de nuevo Parte 2.",
        duration: "24m",
        description:
          "La continuación de la nueva aventura. El grupo se encuentra con nuevos desafíos y un nuevo rival en su camino hacia el gran cielo.",
        img: "https://cdn.jkdesu.com/assets/images/animes/video/image/jkvideo_65f5891fdbd7384e155cdbe37ee412e1.jpg",
        releaseDate: "13/04/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/91.html",
      },
      {
        season: 1,
        number: 92,
        title: "Siguiendo las señales del Rakurium.",
        duration: "24m",
        description:
          "El Rakurium, un artefacto relacionado con Rakua, comienza a emitir señales que guían al grupo hacia otro misterio antiguo.",
        img: "https://image.tmdb.org/t/p/w300/vl99pVo5ZPuLQtTpaLYk0ytFuHh.jpg",
        releaseDate: "19/04/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/92.html",
      },
      {
        season: 1,
        number: 93,
        title: "¡¿Un apoyo total?! ¡¡Enfrentamiento de fans de Gurumin!!.",
        duration: "24m",
        description:
          "Dot se encuentra en medio de una competencia entre dos clubes de fans rivales de Gurumin, y debe mediar para evitar que la situación se salga de control.",
        img: "https://image.tmdb.org/t/p/w300/r4mszAdQEM39STp5smADlbpjnQn.jpg",
        releaseDate: "26/04/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/93.html",
      },
      {
        season: 1,
        number: 94,
        title: "¡La señorita del Centro Pokémon!.",
        duration: "24m",
        description:
          "Mollie, la sanadora del grupo, comparte la historia de cómo decidió convertirse en la 'señorita' del Centro Pokémon a bordo del Valiente Asagi.",
        img: "https://image.tmdb.org/t/p/w300/bd3NKwZKmoMbhweRHW1vWgXAFVS.jpg",
        releaseDate: "03/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/94.html",
      },
      {
        season: 1,
        number: 95,
        title: "¡Esfera Fuerte!.",
        duration: "24m",
        description:
          "Los Tacleadas de Voltios investigan un nuevo misterio relacionado con la energía Teracristal y descubren una extraña Esfera Fuerte que emite un poder inusual.",
        img: "https://image.tmdb.org/t/p/w300/o8c7XFzoYlGIHTWzHohzBXpEOjg.jpg",
        releaseDate: "10/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/95.html",
      },
      {
        season: 1,
        number: 96,
        title: "¡Colisión! La Banda Dragón Explosiva.",
        duration: "24m",
        description:
          "Una banda de entrenadores de tipo Dragón conocida como la 'Banda Dragón Explosiva' desafía a Roy. Es una batalla intensa para probar quién es el mejor entrenador de dragones.",
        img: "https://cdn.jkdesu.com/assets/images/animes/video/image_thumb/jkvideo_66edbe15461d3df54c8eaf3c998d74a4.jpg",
        releaseDate: "17/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/96.html",
      },
      {
        season: 1,
        number: 97,
        title: "¿La encantadora sonrisa del bromista Stunfisk?.",
        duration: "24m",
        description:
          "Un Stunfisk bromista está causando problemas al grupo con sus trampas eléctricas. Deben ser más astutos que el Pokémon para poder continuar su viaje.",
        img: "https://cdn.jkdesu.com/assets/images/animes/video/image_thumb/jkvideo_3cfdea3deff2a099b789026f47c841aa.jpg",
        releaseDate: "31/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/97.html",
      },
      {
        season: 1,
        number: 98,
        title: "¡Reencuentro en Pueblo Cercle!.",
        duration: "24m",
        description:
          "Liko, Roy y Friede llegan a Pueblo Cercle en la región de Paldea. Allí se reencuentran con Dot, quien está investigando un misterioso fenómeno relacionado con Pokémon que no pueden usar sus habilidades.",
        img: "https://image.tmdb.org/t/p/w300/vwCpEvwV4jGhjnWbdxKeYp2mbXV.jpg",
        releaseDate: "07/06/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/98.html",
      },
      {
        season: 1,
        number: 99,
        title: "¡Una Orio que no puede volar y...!.",
        duration: "24m",
        description:
          "Liko y Roy conocen a Orio, una ingeniera mecánica de los Tacleadas de Voltios. Descubren que Orio tiene un problema: ¡su Elekid no puede usar movimientos de tipo Eléctrico!",
        img: "https://image.tmdb.org/t/p/w300/2CxBqwCBj87Izt5lvqiAE4WLBHX.jpg",
        releaseDate: "14/06/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/99.html",
      },
    ],
  },
  {
    id: "pokemon-viajes",
    title: "Pokémon: Viajes",
    img: "frame/Solo-Leveling/T1/1.html.jpg",
    description:
      "La historia final protagonizada por Satoshi y Pikachu para concluir Pokémon (2019). Aquí comienza la cuenta regresiva para despedirnos de Satoshi y Pikachu como protagonistas.",
    genres: ["Aventura"],
    rating: 4.8,
    seasons: 25,
    episodes: 1223,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "ranger-reject",
    title: "Ranger Reject (Sentai Daishikkaku)",
    img: "image/ranger-reject/p.webp",
    description:
      "Con su antiguo escondite y sus jefes aniquilados, los Dusters supervivientes llegan a un acuerdo secreto con el equipo Ranger para participar en el enfrentamiento dominical, uno en el que siempre serán derrotados. ¡Cansado de esta farsa, el Luchador D finalmente da un paso al frente para hacer un cambio de una vez por todas!.",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodes: 19,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 22)), // Hace 22 dias
  },
  {
    id: "dr-stone",
    title: "Dr. STONE",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    description:
      "Un día fatídico, toda la humanidad quedó petrificada por un destello de luz cegadora. Después de varios milenios, el estudiante Taiju despierta y se encuentra perdido en un mundo de estatuas.",
    genres: ["Aventura", "Ciencia Ficción", "Comedia"],
    rating: 4.8,
    seasons: 3,
    episodes: 57,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "one-piece",
    title: "One Piece",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/757bae5a21039bac6ebace5de9affcd8.jpe",
    description:
      "Monkey D. Luffy se niega a que nadie se interponga en su camino para convertirse en el rey de los piratas. ¡Una aventura épica por los mares en busca del tesoro legendario!",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 21,
    episodes: 1100,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 2)), // Hace 2 dias
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f356e33a59518a1a361e6123485c2d43.jpe",
    description:
      "Tanjiro Kamado, un joven de buen corazón, encuentra a su familia masacrada por un demonio. Para empeorar las cosas, su hermana menor, Nezuko, ha sido transformada en un demonio.",
    genres: ["Acción", "Fantasía", "Histórico"],
    rating: 4.9,
    seasons: 4,
    episodes: 55,
    status: "En emisión",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 5)), // Hace 5 dias
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    description:
      "Yuji Itadori se traga un talismán maldito para proteger a sus amigos y ahora comparte su cuerpo con un poderoso demonio. Se une a una sociedad secreta de Hechiceros Jujutsu para cazar maldiciones.",
    genres: ["Acción", "Fantasía", "Escolar"],
    rating: 4.8,
    seasons: 2,
    episodes: 47,
    status: "Finalizado",
    year: 2020,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 3)), // Hace 3 dias
  },
  {
    id: "spy-x-family",
    title: "SPY x FAMILY",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/6b53c5c9676c86f45c81f33775928d3c.jpe",
    description:
      "El maestro espía 'Twilight' debe formar una familia falsa para llevar a cabo una misión. Lo que no sabe es que la 'esposa' que elige es una asesina y la 'hija' es una telépata.",
    genres: ["Acción", "Comedia", "Slice of Life"],
    rating: 4.9,
    seasons: 2,
    episodes: 37,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(), // Hoy
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/b5621ff1277ed6ad1006b0c6f14900bb.jpg",
    heroImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=94,width=1920/cr/landscape_large/d6831c1f-9dba-48db-8bcf-71fe4af5bbee.png",
    logoImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480/cr/logo/acf8d0c2-6c16-447c-aa9c-368d9f3d9900.png",
    trailerUrl: "https://www.youtube.com/embed/xZ0aLMfvYvs?si=SDK7013UdOoP1sxj",
    description:
      "Tras una desastrosa derrota en la Copa Mundial, la Asociación de Fútbol de Japón decide crear un programa de entrenamiento riguroso para encontrar al próximo delantero estrella del país. Trescientos jóvenes talentos compiten en una prisión especial llamada 'Blue Lock', donde el egoísmo es la clave para sobrevivir y convertirse en el mejor.",
    genres: ["Deporte", "Drama"],
    rating: 4.9,
    seasons: 2,
    episodesTotal: 38,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 461)), // Calculado desde el final de la T1
    episodes: [
      // Temporada 1
      {
        season: 1,
        number: 1,
        title: "Sueño",
        duration: "24 min",
        description:
          "Isagi Yoichi es un delantero de preparatoria que no logró llevar a su equipo a las nacionales. De pronto, recibe una invitación para unirse a un proyecto llamado Blue Lock.",
        img: "/image/Blue-lock/1.png",
        releaseDate: "Octubre 9, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "Monstruo",
        duration: "24 min",
        description:
          "La primera selección de Blue Lock comienza. El equipo Z de Isagi debe jugar contra el equipo X en un partido de todos contra todos. Pero antes, deben superar una prueba inesperada.",
        img: "/image/Blue-lock/2.jpg",
        releaseDate: "Octubre 16, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "El 'cero' del fútbol",
        duration: "23 min",
        description:
          "El equipo Z se prepara para su próximo partido contra el equipo Y. Isagi reflexiona sobre su 'arma' y busca la fórmula para marcar su propio gol.",
        img: "/image/Blue-lock/3.png",
        releaseDate: "Octubre 23, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "Premonición e intuición",
        duration: "23 min",
        description:
          "El partido contra el equipo Y llega a su clímax. Isagi y sus compañeros deben encontrar una manera de romper la defensa rival y evitar la eliminación.",
        img: "/image/Blue-lock/4.jpg",
        releaseDate: "Octubre 30, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Para renacer",
        duration: "24 min",
        description:
          "Después de su primera victoria, el Equipo Z debe enfrentarse al Equipo W, que cuenta con los hermanos Wanima y su increíble juego en equipo.",
        img: "/image/Blue-lock/5.jpg",
        releaseDate: "Noviembre 6, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "Lo siento",
        duration: "23 min",
        description:
          "La traición de un compañero pone al Equipo Z en una situación desesperada. Isagi debe encontrar una manera de superar la adversidad y liderar a su equipo.",
        img: "/image/Blue-lock/6.jpg",
        releaseDate: "Noviembre 13, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/6.html",
      },
      {
        season: 1,
        number: 7,
        title: "Subidón",
        duration: "23 min",
        description:
          "El equipo Z está eufórico tras su victoria, pero se enfrentan a su desafío más difícil hasta ahora: el equipo V, el más fuerte de su estrato.",
        img: "/image/Blue-lock/7.jpg",
        releaseDate: "Noviembre 20, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/7.html",
      },
      {
        season: 1,
        number: 8,
        title: "La fórmula para marcar gol",
        duration: "23 min",
        description:
          "El partido contra el equipo V comienza. Nagi, Reo y Zantetsu, el trío de genios, demuestran su abrumadora habilidad, dejando al equipo Z sin respuestas.",
        img: "/image/Blue-lock/8.jpg",
        releaseDate: "Noviembre 27, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/8.html",
      },
      {
        season: 1,
        number: 9,
        title: "El despertar",
        duration: "23 min",
        description:
          "Para sobrevivir, los miembros del equipo Z deben evolucionar. Isagi y Chigiri despiertan sus 'egos' y desatan nuevas habilidades en el campo.",
        img: "/image/Blue-lock/9.jpg",
        releaseDate: "Diciembre 4, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/9.html",
      },
      {
        season: 1,
        number: 10,
        title: "Que se quede así",
        duration: "23 min",
        description:
          "Con el partido empatado, el equipo Z arriesga todo en un último ataque. Isagi debe encontrar la 'fórmula' final para marcar el gol de la victoria.",
        img: "/image/Blue-lock/10.jpg",
        releaseDate: "Diciembre 11, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/10.html",
      },
      {
        season: 1,
        number: 11,
        title: "La última pieza",
        duration: "24 min",
        description:
          "El gol de Isagi asegura la victoria y la clasificación del Equipo Z. Sin embargo, se revela que la primera selección no ha terminado y que aún queda un traidor por eliminar.",
        img: "/image/Blue-lock/11.jpg",
        releaseDate: "Diciembre 18, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/11.html",
      },
      {
        season: 1,
        number: 12,
        title: "La segunda fase",
        duration: "23 min",
        description:
          "Los jugadores que superaron la primera selección avanzan a la segunda fase, donde las pruebas se vuelven individuales y el ego es más importante que nunca.",
        img: "/image/Blue-lock/12.jpg",
        releaseDate: "Diciembre 25, 2022",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/12.html",
      },
      {
        season: 1,
        number: 13,
        title: "Top 3",
        duration: "24 min",
        description:
          "Isagi se une a Bachira y Nagi para la segunda fase. Su primer desafío es un partido de 3 contra 3 contra los mejores jugadores de Blue Lock, incluido el prodigio Rin Itoshi.",
        img: "/image/Blue-lock/13.jpg",
        releaseDate: "Enero 8, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/13.html",
      },
      {
        season: 1,
        number: 14,
        title: "Genios y mediocres",
        duration: "24 min",
        description:
          "El equipo de Isagi es derrotado abrumadoramente por Rin y su equipo. Para seguir avanzando, Isagi debe entender la diferencia entre su talento y el de un verdadero genio.",
        img: "/image/Blue-lock/14.jpg",
        releaseDate: "Enero 15, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/14.html",
      },
      {
        season: 1,
        number: 15,
        title: "Asimilación",
        duration: "23 min",
        description:
          "Isagi, Nagi y Barou se enfrentan a un nuevo equipo. Isagi intenta asimilar las fortalezas de sus compañeros para crear un nuevo tipo de fútbol.",
        img: "/image/Blue-lock/15.jpg",
        releaseDate: "Enero 22, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/15.html",
      },
      {
        season: 1,
        number: 16,
        title: "Fusión triple",
        duration: "24 min",
        description:
          "El egocentrismo de Barou choca con el juego en equipo. Isagi debe encontrar una manera de devorar el ego de Barou para que su equipo pueda funcionar.",
        img: "/image/Blue-lock/16.jpg",
        releaseDate: "Enero 29, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/16.html",
      },
      {
        season: 1,
        number: 17,
        title: "Paquete",
        duration: "24 min",
        description:
          "Isagi y su equipo se enfrentan a Chigiri, Kunigami y Reo. Es una batalla de viejos compañeros convertidos en rivales.",
        img: "/image/Blue-lock/17.jpg",
        releaseDate: "Febrero 5, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/17.html",
      },
      {
        season: 1,
        number: 18,
        title: "El escenario de la estrella",
        duration: "24 min",
        description:
          "Barou, el 'Rey', despierta como un villano en el campo, anotando goles espectaculares. Isagi debe devorar al nuevo rey para convertirse en el protagonista.",
        img: "/image/Blue-lock/18.jpg",
        releaseDate: "Febrero 12, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/18.html",
      },
      {
        season: 1,
        number: 19,
        title: "Dancing boy",
        duration: "24 min",
        description:
          "El equipo de Isagi se prepara para la revancha contra Rin, Aryu y Tokimitsu. Bachira, que fue elegido por el equipo de Rin, ahora es su oponente.",
        img: "/image/Blue-lock/19.jpg",
        releaseDate: "Febrero 19, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/19.html",
      },
      {
        season: 1,
        number: 20,
        title: "Superjuego combinado",
        duration: "23 min",
        description:
          "Comienza el partido de 4 contra 4. Isagi, Nagi y Barou deben combinar sus egos evolucionados para tener una oportunidad contra el equipo de Rin.",
        img: "/image/Blue-lock/20.jpg",
        releaseDate: "Febrero 26, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/20.html",
      },
      {
        season: 1,
        number: 21,
        title: "No estoy ahí",
        duration: "24 min",
        description:
          "Isagi se siente abrumado por el nivel de juego de Rin y Bachira. Para poder competir, debe encontrar una nueva forma de pensar y de jugar.",
        img: "/image/Blue-lock/21.jpg",
        releaseDate: "Marzo 5, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/21.html",
      },
      {
        season: 1,
        number: 22,
        title: "La voz",
        duration: "24 min",
        description:
          "Isagi comienza a entender el concepto de 'suerte' en el fútbol. Escuchando la voz de su instinto, se posiciona para devorar el gol decisivo.",
        img: "/image/Blue-lock/22.jpg",
        releaseDate: "Marzo 12, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/22.html",
      },
      {
        season: 1,
        number: 23,
        title: "Suerte",
        duration: "24 min",
        description:
          "Con el partido en su punto álgido, Isagi finalmente se pone al nivel de Rin. Es una batalla de egos donde la suerte determinará al ganador.",
        img: "/image/Blue-lock/23.jpe",
        releaseDate: "Marzo 19, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/23.html",
      },
      {
        season: 1,
        number: 24,
        title: "Ha llegado la hora",
        duration: "24 min",
        description:
          "Finaliza la segunda selección. Los supervivientes se enfrentan a un nuevo desafío: un partido contra la selección japonesa Sub-20, con el destino de Blue Lock en juego.",
        img: "/image/Blue-lock/24.jpe",
        releaseDate: "Marzo 26, 2023",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T1/24.html",
      },
      // Temporada 2
      {
        season: 2,
        number: 25,
        title: "Pruebas",
        duration: "25 min",
        description:
          "Comienza el partido contra la Sub-20. Los jugadores de Blue Lock deben demostrar que su fútbol egoísta es superior al juego en equipo tradicional de Japón.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/48b0f6925194cb17b1c3a04db86e1d30.jpg",
        releaseDate: "Octubre 5, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/25.html",
      },
      {
        season: 2,
        number: 26,
        title: "El asesino y el ninja",
        duration: "23 min",
        description:
          "Shidou Ryusei, el 'demonio' de Blue Lock, entra al campo y desata su juego explosivo y destructivo, poniendo en aprietos a la defensa de la Sub-20.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/d6251408312519875a679a79349b569e.jpg",
        releaseDate: "Octubre 12, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/26.html",
      },
      {
        season: 2,
        number: 27,
        title: "Un mundo de sensaciones",
        duration: "23 min",
        description:
          "Sae Itoshi, el hermano prodigio de Rin, entra en escena y demuestra por qué es considerado uno de los mejores jugadores del mundo, cambiando el rumbo del partido.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/e23ae24be4332922cc83c1221c23d799.jpg",
        releaseDate: "Octubre 19, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/27.html",
      },
      {
        season: 2,
        number: 28,
        title: "Camaleón",
        duration: "25 min",
        description:
          "Niko Ikki, el 'camaleón' de Blue Lock, utiliza su increíble visión y capacidad de análisis para leer los movimientos de Sae y detener el avance de la Sub-20.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/346304b4a253bfe85053c9ef9b9bcb5b.jpg",
        releaseDate: "Octubre 26, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/28.html",
      },
      {
        season: 2,
        number: 29,
        title: "Flujo",
        duration: "25 min",
        description:
          "Para competir contra Sae, Isagi debe entrar en un estado de 'flujo', una inmersión total en el juego que le permite anticipar y reaccionar a un nivel sobrehumano.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/c86f867e11a89f4957aa2ac538406528.jpg",
        releaseDate: "Noviembre 2, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/29.html",
      },
      {
        season: 2,
        number: 30,
        title: "El gran escenario",
        duration: "24 min",
        description:
          "El partido se convierte en un escenario donde los mejores egoístas brillan. Es una batalla de ida y vuelta donde cada jugador intenta imponer su propia visión del gol.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/912854302314ba7d029d36948aaa4e05.jpg",
        releaseDate: "Noviembre 9, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/30.html",
      },
      {
        season: 2,
        number: 31,
        title: "Sae Itoshi",
        duration: "24 min",
        description:
          "Se revela el pasado de los hermanos Itoshi y la razón de su rivalidad. Rin está decidido a derrotar a Sae para demostrarle que su fútbol no estaba equivocado.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/0c0e8587d8bc5886f30a5257fa85319d.jpg",
        releaseDate: "Noviembre 16, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/31.html",
      },
      {
        season: 2,
        number: 32,
        title: "Genes Azules",
        duration: "24 min",
        description:
          "La batalla entre los hermanos Itoshi llega a su punto más álgido. Rin y Sae demuestran por qué llevan los 'genes' del mejor fútbol del mundo.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/204aa539eb32c594490105be9f6b318d.jpg",
        releaseDate: "Noviembre 23, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/32.html",
      },
      {
        season: 2,
        number: 33,
        title: "Nieve nocturna",
        duration: "25 min",
        description:
          "Isagi, en estado de flujo, lee el campo a un nivel superior, anticipando incluso los movimientos de los hermanos Itoshi. Se convierte en el verdadero cerebro del equipo Blue Lock.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/db534eb9a35f2675158432ee9b8c187e.jpg",
        releaseDate: "Noviembre 30, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/33.html",
      },
      {
        season: 2,
        number: 34,
        title: "Cambios",
        duration: "25 min",
        description:
          "Con el tiempo agotándose, ambos equipos realizan cambios estratégicos. Barou entra al campo, listo para devorar a todos y convertirse en el protagonista del partido.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/c903f2755bd7396a0e863fbe31cd4c7e.jpg",
        releaseDate: "Diciembre 7, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/34.html",
      },
      {
        season: 2,
        number: 35,
        title: "Lo que nos enseñaste",
        duration: "25 min",
        description:
          "El ego de Isagi se enfrenta directamente al de Rin. Isagi utiliza todo lo que ha aprendido en Blue Lock para crear una última oportunidad de gol.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/19714f0b51dab6f1ddedca01bb1a3c2a.jpg",
        releaseDate: "Diciembre 14, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/35.html",
      },
      {
        season: 2,
        number: 36,
        title: "Flor",
        duration: "25 min",
        description:
          "En la jugada final, la 'suerte' sonríe a uno de los egoístas. Isagi marca el gol de la victoria, y el proyecto Blue Lock toma el control de la selección japonesa.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/207f4bddb4dc35d06b8c799c6207f180.jpg",
        releaseDate: "Diciembre 21, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/36.html",
      },
      {
        season: 2,
        number: 37,
        title: "No estoy solo",
        duration: "24 min",
        description:
          "Después del partido, los jugadores de Blue Lock disfrutan de un breve descanso. Isagi reflexiona sobre su evolución y los lazos que ha formado.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/397c7e52ad740980b910cf7a6bdffdb4.jpg",
        releaseDate: "Diciembre 28, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/37.html",
      },
      {
        season: 2,
        number: 38,
        title: "Golpe de gracia",
        duration: "23 min",
        description:
          "Ego Jinpachi presenta la siguiente fase: La Liga Neo Egoísta, donde los jugadores de Blue Lock competirán junto a los mejores jugadores jóvenes del mundo. Comienza una nueva era.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=70,width=320,height=180/catalog/crunchyroll/6feb4e321d81efa0b5f64b557149efdf.jpg",
        releaseDate: "Diciembre 28, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Blue-Lock/T2/38.html",
      },
    ],
  },
];

export const newEpisodes = [
  {
    id: 1,
    title: "I've Been Killing Slimes For 300 Years",
    meta: "Episodio 5 • Sub | Dob",
    time: "14:00",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/fa62dd1fc7a9bc0b587f36f53bf572c1.jpg",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire1/b753dcccb08721820482a868353388f61618002633_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 5,
  },
  {
    id: 2,
    title: "Private Tutor to the Duke's Daughter",
    meta: "Episodio 1 • Subtitulado",
    time: "12:00",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/36181b3b55c6b841315842838423403a.jpe",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire2/d6c810e46c1f10255c27f31ab2c24c7e1720377038_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 1,
  },
  {
    title: "Classic Stars",
    meta: "Episodio 13",
    time: "12:15",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/d719910d5538e1b343a4155b1784d1a0.jpe",
    url: "#",
    day: "hoy",
  },
  {
    title: "Dr. STONE",
    meta: "Episodio 12 • Sub | Dob",
    time: "15:00",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    url: "#",
    day: "ayer",
  },
  {
    title: "Jujutsu Kaisen",
    meta: "Episodio 24 • Subtitulado",
    time: "18:30",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    url: "#",
    day: "ayer",
  },
];
