{
  season: 1,
  number: 64,
  title: "El monte Nappe y las sombras sigilosas.",
  duration: "24m",
  description: "Mientras entrenan en el Monte Nappe, unas misteriosas sombras comienzan a acechar al grupo. Deben descubrir qué son y cuáles son sus intenciones.",
  img: "/image/Pokemon-Horizons/64.jpg",
  releaseDate: "07/09/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/64"
},
{
  season: 1,
  number: 65,
  title: "¡Liko y Amenthio!.",
  duration: "24m",
  description: "Liko tiene un encuentro inesperado con Amethio de los Exploradores. Esta vez, sin una batalla inminente, tienen una conversación que podría cambiar su rivalidad.",
  img: "/image/Pokemon-Horizons/65.jpg",
  releaseDate: "14/09/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/65"
},
{
  season: 1,
  number: 66,
  title: "¡Ruptura del sistema! ¡¡Crisis en la Academia Naranja!!.",
  duration: "24m",
  description: "Un virus informático ataca el sistema de la Academia Naranja. Dot, junto con Penny, debe usar sus habilidades de hacking para detener la crisis.",
  img: "/image/Pokemon-Horizons/66.jpg",
  releaseDate: "21/09/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/66"
},
{
  season: 1,
  number: 67,
  title: "¡¡Brilla, Teracristalización!! ¡Liko VS Roy!.",
  duration: "24m",
  description: "Como parte de su examen final en la academia, Liko y Roy se enfrentan en una batalla Teracristal para demostrar todo lo que han aprendido.",
  img: "/image/Pokemon-Horizons/67.jpg",
  releaseDate: "28/09/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/67"
},
{
  season: 1,
  number: 68,
  title: "¡Hacia un Nuevo Cielo! ¡¡El Valiente Asagi!!.",
  duration: "24m",
  description: "Con su entrenamiento en Paldea completo, los Tacleadas de Voltios se preparan para una nueva aventura, zarpando en el Valiente Asagi hacia un destino desconocido.",
  img: "/image/Pokemon-Horizons/68.jpg",
  releaseDate: "12/10/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/68"
},
{
  season: 1,
  number: 69,
  title: "¡¿Yo soy un Pokémon y tú eres yo?!.",
  duration: "24m",
  description: "Un extraño fenómeno causa que Liko y Sprigatito intercambien cuerpos. Deben aprender a vivir en el cuerpo del otro mientras buscan una solución.",
  img: "/image/Pokemon-Horizons/69.jpg",
  releaseDate: "19/10/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/69"
},
{
  season: 1,
  number: 70,
  title: "¡El martillo de Tinkatink no se construyó en un día!.",
  duration: "24m",
  description: "El grupo se encuentra de nuevo con el Tinkatink, que ahora lidera a su clan. Dot se inspira en su perseverancia y trabajo duro.",
  img: "https://image.tmdb.org/t/p/w300/fpF9oWhAYC38yjcQ4rIvFMszJrM.jpg",
  releaseDate: "26/10/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/70"
},
{
  season: 1,
  number: 71,
  title: "Encuentro en el Lago Cristalino.",
  duration: "24m",
  description: "Terapagos guía al grupo a un lago cristalino donde se encuentran con un Pokémon legendario que parece tener una conexión con Lucius.",
  img: "https://image.tmdb.org/t/p/w300/d1RfarxY2lxEqX8gwADZqg6fNkr.jpg",
  releaseDate: "02/11/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/71"
},
{
  season: 1,
  number: 72,
  title: "¡Persecución! ¡¡Encuentren a Kleavor!!.",
  duration: "24m",
  description: "Un Kleavor, otro de los Pokémon de Lucius, está causando estragos. Roy, inspirado por las leyendas, se propone calmar al Pokémon hacha.",
  img: "/image/Pokemon-Horizons/72.jpg",
  releaseDate: "09/11/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/72"
},
{
  season: 1,
  number: 73,
  title: "Kleavor, el guerrero solitario.",
  duration: "24m",
  description: "Roy logra conectar con Kleavor, entendiendo su soledad y su deseo de probar su fuerza. Se gana el respeto del Pokémon y una nueva pista sobre Lucius.",
  img: "/image/Pokemon-Horizons/73.jpg",
  releaseDate: "16/11/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/73"
},
{
  season: 1,
  number: 74,
  title: "Los tres Exploradores.",
  duration: "24m",
  description: "Se revela más sobre los administradores de los Exploradores. Coral, Sidian y Chalce muestran sus personalidades y sus poderosos Pokémon en una misión.",
  img: "/image/Pokemon-Horizons/74.jpg",
  releaseDate: "23/11/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/74"
},
{
  season: 1,
  number: 75,
  title: "El futuro que se nos ha confiado, el brillo de este mundo.",
  duration: "24m",
  description: "Reflexionando sobre su viaje, Liko y Roy comprenden la gran responsabilidad que tienen para proteger a Terapagos y descubrir los secretos de Lucius.",
  img: "https://image.tmdb.org/t/p/w300/qU9MzSOKQDDEfLYu1ES0wpH72EA.jpg",
  releaseDate: "30/11/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/75"
},
{
  season: 1,
  number: 76,
  title: "¿Sonano? ¡Sodayo!.",
  duration: "24m",
  description: "El grupo se encuentra con un Wobbuffet y un Wynaut que siempre parecen estar de acuerdo. Su dinámica enseña a Liko y Roy sobre la comunicación y el trabajo en equipo.",
  img: "/image/Pokemon-Horizons/76.jpg",
  releaseDate: "07/12/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/76"
},
{
  season: 1,
  number: 77,
  title: "Randou regresa a su ciudad natal.",
  duration: "24m",
  description: "Landau, el pescador y miembro de los Tacleadas de Voltios, regresa a su hogar, donde el grupo aprende más sobre su pasado y su familia.",
  img: "https://image.tmdb.org/t/p/w300/6W6vnq3MP4gQIWpXKnhajzFj3cU.jpg",
  releaseDate: "14/12/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/77"
},
{
  season: 1,
  number: 78,
  title: "¡Feroz batalla con Entei! ¡¡Rugido de Fuego!!.",
  duration: "24m",
  description: "El Entei de Lucius aparece, y su poder es abrumador. Roy y Crocalor deben desatar todo su poder de fuego para enfrentarse al Pokémon legendario.",
  img: "https://image.tmdb.org/t/p/w300/gF4m1k9K8dZ7A3rkneLxSSziGyA.jpg",
  releaseDate: "21/12/24",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/78"
},
{
  season: 1,
  number: 79,
  title: "Más allá de la cima.",
  duration: "24m",
  description: "Tras la batalla con Entei, Roy se da cuenta de que todavía hay un largo camino por recorrer para alcanzar su sueño de derrotar a Rayquaza.",
  img: "/image/Pokemon-Horizons/79.jpg",
  releaseDate: "11/01/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/79"
},
{
  season: 1,
  number: 80,
  title: "¡¿Pokémon asombrosos en el Área Cero?!.",
  duration: "24m",
  description: "El grupo finalmente se aventura en el misterioso Área Cero, donde encuentran Pokémon del pasado y del futuro, y se acercan más al secreto de Terapagos.",
  img: "/image/Pokemon-Horizons/80.jpg",
  releaseDate: "18/01/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/80"
},
{
  season: 1,
  number: 81,
  title: "¡Una gran batalla! ¡El fuego que arrasa la tierra!.",
  duration: "24m",
  description: "En el corazón del Área Cero, los Tacleadas de Voltios se enfrentan a un poderoso Pokémon Paradoja que amenaza con desestabilizar todo el lugar.",
  img: "/image/Pokemon-Horizons/81.jpg",
  releaseDate: "25/01/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/81"
},
{
  season: 1,
  number: 82,
  title: "¡Al final de un arcoíris brillante!.",
  duration: "24m",
  description: "Una pista sobre el último de los seis héroes de Lucius lleva al grupo a un lugar donde se dice que el final de un arcoíris toca la tierra.",
  img: "https://image.tmdb.org/t/p/w300/lvHdjB7yEFzIFe9FSO7ixKss5U9.jpg",
  releaseDate: "01/02/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/82"
},
{
  season: 1,
  number: 83,
  title: "¿La verdad es revelada? ¡La determinación de Amethio!.",
  duration: "24m",
  description: "Amethio, siguiendo sus propias pistas, descubre una verdad impactante sobre los Exploradores y su misión, lo que lo lleva a tomar una decisión crucial.",
  img: "https://image.tmdb.org/t/p/w300/do0cpvRMGZkJiVpPrUKcCg48knG.jpg",
  releaseDate: "08/02/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/83"
},
{
  season: 1,
  number: 84,
  title: "¡El lugar donde el cielo y la tierra se encuentran!.",
  duration: "24m",
  description: "Terapagos finalmente revela la ubicación de Rakua, el paraíso soñado por Lucius. El grupo se prepara para el tramo final de su viaje.",
  img: "/image/Pokemon-Horizons/84.jpg",
  releaseDate: "15/02/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/84"
},
{
  season: 1,
  number: 85,
  title: "¡Llegamos! ¡El paraíso, Rakua!.",
  duration: "24m",
  description: "Los Tacleadas de Voltios llegan a Rakua, un lugar maravilloso y misterioso. Sin embargo, los Exploradores no se quedan atrás.",
  img: "https://image.tmdb.org/t/p/w300/ukjIXhW8vOl53zGdKZUzdw5C4HL.jpg",
  releaseDate: "22/02/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/85"
},
{
  season: 1,
  number: 86,
  title: "¡Los Tacleada de Voltios en ascenso VS los Exploradores!.",
  duration: "24m",
  description: "La batalla final entre los Tacleadas de Voltios y los Exploradores por el destino de Terapagos y Rakua comienza.",
  img: "https://image.tmdb.org/t/p/w300/vUA4oDiMKVmdQ1fQ4E0uAqhFwwZ.jpg",
  releaseDate: "01/03/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/86"
},
{
  season: 1,
  number: 87,
  title: "La guía del Rayquaza negro.",
  duration: "24m",
  description: "El Rayquaza negro reaparece, pero esta vez no como un enemigo, sino como una guía que muestra el verdadero propósito de Terapagos.",
  img: "/image/Pokemon-Horizons/87.jpg",
  releaseDate: "08/03/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/87"
},
{
  season: 1,
  number: 88,
  title: "El Zygarde Blanco que sacude la tierra.",
  duration: "24m",
  description: "El último de los seis héroes se revela: un majestuoso Zygarde de color blanco que ha estado protegiendo el equilibrio de la tierra.",
  img: "https://image.tmdb.org/t/p/w300/9MPNahmqX45yqtZiX2w1ufD6RPe.jpg",
  releaseDate: "15/03/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/88"
},
{
  season: 1,
  number: 89,
  title: "¡Más allá de la aventura!.",
  duration: "24m",
  description: "Con el misterio de Lucius resuelto, Liko y Roy miran hacia el futuro, listos para embarcarse en nuevas aventuras con sus amigos y Pokémon.",
  img: "https://image.tmdb.org/t/p/w300/7F6CvGQANnr521wVIMNHN1wkUOy.jpg",
  releaseDate: "22/03/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/89"
},
{
  season: 1,
  number: 90,
  title: "Hacia el gran cielo, de nuevo Parte 1.",
  duration: "24m",
  description: "Una nueva trama comienza cuando los Tacleadas de Voltios reciben una nueva misión que los llevará a una región inexplorada.",
  img: "https://image.tmdb.org/t/p/w300/luf4FhAZRs8GfwguAs7V41xUNiP.jpg",
  releaseDate: "12/04/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/90"
},
{
  season: 1,
  number: 91,
  title: "Hacia el gran cielo, de nuevo Parte 2.",
  duration: "24m",
  description: "La continuación de la nueva aventura. El grupo se encuentra con nuevos desafíos y un nuevo rival en su camino hacia el gran cielo.",
  img: "https://cdn.jkdesu.com/assets/images/animes/video/image/jkvideo_65f5891fdbd7384e155cdbe37ee412e1.jpg",
  releaseDate: "13/04/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/91"
},
{
  season: 1,
  number: 92,
  title: "Siguiendo las señales del Rakurium.",
  duration: "24m",
  description: "El Rakurium, un artefacto relacionado con Rakua, comienza a emitir señales que guían al grupo hacia otro misterio antiguo.",
  img: "https://image.tmdb.org/t/p/w300/vl99pVo5ZPuLQtTpaLYk0ytFuHh.jpg",
  releaseDate: "19/04/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/92"
},
{
  season: 1,
  number: 93,
  title: "¡¿Un apoyo total?! ¡¡Enfrentamiento de fans de Gurumin!!.",
  duration: "24m",
  description: "Dot se encuentra en medio de una competencia entre dos clubes de fans rivales de Gurumin, y debe mediar para evitar que la situación se salga de control.",
  img: "https://image.tmdb.org/t/p/w300/r4mszAdQEM39STp5smADlbpjnQn.jpg",
  releaseDate: "26/04/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/93"
},
{
  season: 1,
  number: 94,
  title: "¡La señorita del Centro Pokémon!.",
  duration: "24m",
  description: "Mollie, la sanadora del grupo, comparte la historia de cómo decidió convertirse en la 'señorita' del Centro Pokémon a bordo del Valiente Asagi.",
  img: "https://image.tmdb.org/t/p/w300/bd3NKwZKmoMbhweRHW1vWgXAFVS.jpg",
  releaseDate: "03/05/25",
  language: "Subtitulado",
  videoUrl: "https://all-anime.net/ver/Pokemon-horizons/T1/94"
},