// --- BASE DE DATOS DE ANIMES ---
// En un proyecto real, esto vendría de un servidor o una API.

export const animeData = [
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f2d6d93f5ba4a24bcb3b0d1322a645ff.jpg",
    heroImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=94,width=1920/CurationAssets/Solo%20Leveling/SEASON%202/ULTRA-WIDE/SoloLeveling-S2-KV1-UW-LTR.png",
    logoImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480/keyart/GDKHZEJ0K-title_logo-en-us",
    trailerUrl: "https://www.youtube.com/embed/TceDFwPXCuI?si=Pwe8qBK_wKzIZ6a7",
    description:
      "Conocido como el cazador más débil de la humanidad, se encuentra en una lucha constante por la supervivencia. Después de una experiencia cercana a la muerte, adquiere un poder único para subir de nivel.",
    genres: ["Acción", "Aventura", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodesTotal: 25,
    status: "Finalizado",
    year: 2024,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 122)), // Hace 122 dias
    episodes: [
      {
        season: 1,
        number: 1,
        title: "Estoy acostumbrado",
        duration: "23 min",
        description:
          "A Jin-Woo Sung lo conocen el cazador más débil de la humanidad, lo que lo convierte en objeto de burla de sus compañeros, aunque Ju-Hee Lee, una joven sanadora, siempre se preocupa por él y le ayuda a hacer amigos.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/9685e02cab2b3d22296e7c7e46d78aa8.jpe",
        releaseDate: "Enero 6, 2024",
        episodeNumber: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "Si tuviera una oportunidad más",
        duration: "23 min",
        description:
          "Jin-Woo y sus compañeros están atrapados y no pueden hacer nada mientras la estatua de piedra los masacra uno a uno. Parece que hay una salida a este pérfido juego, pero ¿a qué precio?",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/50a0eb40c919b8efea01fd4799df08ff.jpe",
        releaseDate: "Enero 13, 2024",
        episodeNumber: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "Es como un videojuego",
        duration: "24 min",
        description:
          "Para su sorpresa, Jin-Woo se despierta sano y salvo en el hospital. Al principio cree que los horripilantes sucesos que ha vivido son un sueño, pero las pantallas de estado no desaparecen y no parecen ser visibles para nadie más.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/c6adceca173ff32ae979af193a476fb2.jpe",
        releaseDate: "Enero 20, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "Tengo que hacerme más fuerte",
        duration: "24 min",
        description:
          "En un mundo donde portales misteriosos conectan con mazmorras llenas de monstruos, Sung Jin-Woo lucha por sobrevivir como el cazador más débil.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/78de61960488c9f16f960dae0b554eca.jpe",
        releaseDate: "Enero 27, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Un muy buen trato",
        duration: "24 min",
        description:
          "Cuando Jinwoo sale del hospital, las enfermeras se fijan en su buen estado físico. ¿Siempre tuvo tan buen cuerpo? Poco después, un grupo de Cazadores de rango C buscan un par de compañeros para rellenar y poder entrar a una mazmorra también C, así que como le ofrecen una buena cantidad, acepta.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/403416c5837765866f3b19ac27932777.jpe",
        releaseDate: "Febrero 3, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "Comienza la verdadera caza",
        duration: "24 min",
        description:
          "Jinwoo cae en la trampa que su nuevo equipo temporal le tiende y tiene que sobrevivir como puede, una vez más, ante un monstruo mucho más poderoso que él. A su lado está Jinho, a quien también han abandonado.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/4622fd0dd6f0072211526a8ae67f0c5c.jpe",
        releaseDate: "Febrero 10, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7,
        title: "Veamos hasta dónde puedo llegar",
        duration: "24 min",
        description:
          "Tras el incidente en la mazmorra de rango C, Jinwoo sigue con su vida como siempre, aunque su hermana no acaba de creer la gran evolución de su hermano.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/018425874ef4c1b18b32c26645d6c848.jpe",
        releaseDate: "Febrero 17, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7.5,
        title: "Episodio especial",
        duration: "24 min",
        description: "Repasamos la historia hasta el momento.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/693c3c2259bf67d2afd151453ff15e1d.jpe",
        releaseDate: "Febrero 24, 2024",
        language: "Subtitulado",
        videoUrl: "/frame/Solo-Leveling/T1/1.html.html",
      },
      {
        season: 1,
        number: 8,
        title: "Esto es frustrante",
        duration: "24 min",
        description:
          "Tras su última incursión en una mazmorra, Jinwoo se ha dado cuenta de su propia debilidad. Quiere subir de nivel lo antes posible, pero eso podrá hacerlo si consigue entrar en las mazmorras.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/ba4454c313d44737a3a72fc390bd2159.jpe",
        releaseDate: "Marzo 2, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 9,
        title: "Has estado ocultando tus habilidades",
        duration: "24 min",
        description:
          "El grupo de supervivientes de la mazmorra doble entra en la mazmorra junto a los presos condenados y Kang Taeshik, el cazador encargado de supervisar a los prisioneros. Sin embargo, lo que parecía un viaje normal a una mazmorra acaba siendo un río de sangre.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/08ade842ca3ae544ccc5e4f6a207b529.jpe",
        releaseDate: "Marzo 9, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 10,
        title: "¿Qué es esto, un pícnic?",
        duration: "24 min",
        description:
          "Jinwoo y Jinho preparan un grupo repleto de figurantes para entrar ellos solos a las mazmorras y conseguir dinero, pero esto hace que Tigre Blanco se fije en las posibles capacidades de Jinwoo y sospechen de que vivió un segundo despertar.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/9833d2909af5311139e79b32a44d9605.jpe",
        releaseDate: "Marzo 16, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 11,
        title: "11. Un caballero defendiendo un trono vacío",
        duration: "24 min",
        description:
          "Sung Jinwoo inicia la misión para cambiar de clase y se enfrenta a un enemigo formidable. Mientras, Jinho se reúne con su familia y otros cazadores visitan la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/66e3cabc8e0557f77c93c24178e7a5cd.jpe",
        releaseDate: "Marzo 23, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 12,
        title: "12. Surge",
        duration: "24 min",
        description:
          "Mientras Jinwoo se enfrenta a sí mismo e intenta completar el cambio de clase, Choi Jong-in y los cazadores que lo acompañan descubren algo en la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,fit=contain,width=320,height=180,quality=70/catalog/crunchyroll/cda77a98de7021522ebb5f0cc9bebd7d.jpe",
        releaseDate: "Marzo 30, 2024",
        language: "Sub | Dob",
        videoUrl: "/frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 2,
        number: 25,
        title: "Al siguiente objetivo",
        duration: "23 min",
        img: "https://img1.ak.crunchyroll.com/i/spire1/1a293b685a23d4f8fc4152912a7288f31690858883_main.jpg",
      },
      {
        season: 2,
        number: 24,
        title: "¿Eres el rey de los humanos?",
        duration: "23 min",
        img: "https://img1.ak.crunchyroll.com/i/spire4/e7887411c401319d67554559383679631689625399_main.jpg",
      },
    ],
  },
  {
    id: "pokemon-horizons",
    title: "Pokémon: Horizons",
    img: "https://cdn.jkdesu.com/assets/images/animes/image/pokemon-shinsaku-anime.jpg",
    description:
      "Pocket Mosnters es una historia sobre dos misteriosos personajes de Pokémon, Liko y Roy, que están enredados en el mundo de Pokémon. Sus aventuras y destinos cambiarán a medida que se encuentren con nuevas criaturas y encuentros.",
    genres: ["Aventura"],
    rating: 4.9,
    seasons: 1,
    episodes: 99,
    status: "En emisión",
    year: 2024,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(), // Hoy
  },
  {
    id: "pokemon-viajes",
    title: "Pokémon: Viajes",
    img: "/frame/Solo-Leveling/T1/1.html.jpg",
    description:
      "La historia final protagonizada por Satoshi y Pikachu para concluir Pokémon (2019). Aquí comienza la cuenta regresiva para despedirnos de Satoshi y Pikachu como protagonistas.",
    genres: ["Aventura"],
    rating: 4.8,
    seasons: 25,
    episodes: 1223,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "ranger-reject",
    title: "Ranger Reject (Sentai Daishikkaku)",
    img: "/image/ranger-reject/p.webp",
    description:
      "Con su antiguo escondite y sus jefes aniquilados, los Dusters supervivientes llegan a un acuerdo secreto con el equipo Ranger para participar en el enfrentamiento dominical, uno en el que siempre serán derrotados. ¡Cansado de esta farsa, el Luchador D finalmente da un paso al frente para hacer un cambio de una vez por todas!.",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodes: 19,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 22)), // Hace 22 dias
  },
  {
    id: "dr-stone",
    title: "Dr. STONE",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    description:
      "Un día fatídico, toda la humanidad quedó petrificada por un destello de luz cegadora. Después de varios milenios, el estudiante Taiju despierta y se encuentra perdido en un mundo de estatuas.",
    genres: ["Aventura", "Ciencia Ficción", "Comedia"],
    rating: 4.8,
    seasons: 3,
    episodes: 57,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "one-piece",
    title: "One Piece",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/757bae5a21039bac6ebace5de9affcd8.jpe",
    description:
      "Monkey D. Luffy se niega a que nadie se interponga en su camino para convertirse en el rey de los piratas. ¡Una aventura épica por los mares en busca del tesoro legendario!",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 21,
    episodes: 1100,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 2)), // Hace 2 dias
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f356e33a59518a1a361e6123485c2d43.jpe",
    description:
      "Tanjiro Kamado, un joven de buen corazón, encuentra a su familia masacrada por un demonio. Para empeorar las cosas, su hermana menor, Nezuko, ha sido transformada en un demonio.",
    genres: ["Acción", "Fantasía", "Histórico"],
    rating: 4.9,
    seasons: 4,
    episodes: 55,
    status: "En emisión",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 5)), // Hace 5 dias
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    description:
      "Yuji Itadori se traga un talismán maldito para proteger a sus amigos y ahora comparte su cuerpo con un poderoso demonio. Se une a una sociedad secreta de Hechiceros Jujutsu para cazar maldiciones.",
    genres: ["Acción", "Fantasía", "Escolar"],
    rating: 4.8,
    seasons: 2,
    episodes: 47,
    status: "Finalizado",
    year: 2020,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 3)), // Hace 3 dias
  },
  {
    id: "spy-x-family",
    title: "SPY x FAMILY",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/6b53c5c9676c86f45c81f33775928d3c.jpe",
    description:
      "El maestro espía 'Twilight' debe formar una familia falsa para llevar a cabo una misión. Lo que no sabe es que la 'esposa' que elige es una asesina y la 'hija' es una telépata.",
    genres: ["Acción", "Comedia", "Slice of Life"],
    rating: 4.9,
    seasons: 2,
    episodes: 37,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(), // Hoy
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/b5621ff1277ed6ad1006b0c6f14900bb.jpg",
    description:
      "Tras una desastrosa derrota en el Mundial, 300 de los mejores delanteros de Japón son reunidos en una instalación similar a una prisión llamada 'Blue Lock' para crear al delantero más egoísta del mundo.",
    genres: ["Deportes", "Drama"],
    rating: 4.7,
    seasons: 1,
    episodes: 24,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje", "agregado"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 38)), // Hace 38 dias
  },
];

export const newEpisodes = [
  {
    id: 1,
    title: "I've Been Killing Slimes For 300 Years",
    meta: "Episodio 5 • Sub | Dob",
    time: "14:00",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/fa62dd1fc7a9bc0b587f36f53bf572c1.jpg",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire1/b753dcccb08721820482a868353388f61618002633_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 5,
  },
  {
    id: 2,
    title: "Private Tutor to the Duke's Daughter",
    meta: "Episodio 1 • Subtitulado",
    time: "12:00",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/36181b3b55c6b841315842838423403a.jpe",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire2/d6c810e46c1f10255c27f31ab2c24c7e1720377038_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 1,
  },
  {
    title: "Classic Stars",
    meta: "Episodio 13",
    time: "12:15",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/d719910d5538e1b343a4155b1784d1a0.jpe",
    url: "#",
    day: "hoy",
  },
  {
    title: "Dr. STONE",
    meta: "Episodio 12 • Sub | Dob",
    time: "15:00",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    url: "#",
    day: "ayer",
  },
  {
    title: "Jujutsu Kaisen",
    meta: "Episodio 24 • Subtitulado",
    time: "18:30",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    url: "#",
    day: "ayer",
  },
];
