// --- BASE DE DATOS DE ANIMES ---
// En un proyecto real, esto vendría de un servidor o una API.

export const animeData = [
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f2d6d93f5ba4a24bcb3b0d1322a645ff.jpg",
    heroImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=94,width=1920/CurationAssets/Solo%20Leveling/SEASON%202/ULTRA-WIDE/SoloLeveling-S2-KV1-UW-LTR.png",
    logoImg:
      "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480/keyart/GDKHZEJ0K-title_logo-en-us",
    trailerUrl: "https://www.youtube.com/embed/TceDFwPXCuI?si=Pwe8qBK_wKzIZ6a7",
    description:
      "Conocido como el cazador más débil de la humanidad, se encuentra en una lucha constante por la supervivencia. Después de una experiencia cercana a la muerte, adquiere un poder único para subir de nivel.",
    genres: ["Acción", "Aventura", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodesTotal: 25,
    status: "Finalizado",
    year: 2024,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 122)), // Hace 122 dias
    episodes: [
      {
        season: 1,
        number: 1,
        title: "Estoy acostumbrado",
        duration: "23 min",
        description:
          "A Jin-Woo Sung lo conocen el cazador más débil de la humanidad, lo que lo convierte en objeto de burla de sus compañeros, aunque Ju-Hee Lee, una joven sanadora, siempre se preocupa por él y le ayuda a hacer amigos.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/9685e02cab2b3d22296e7c7e46d78aa8.jpe",
        releaseDate: "Enero 6, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "Si tuviera una oportunidad más",
        duration: "23 min",
        description:
          "Jin-Woo y sus compañeros están atrapados y no pueden hacer nada mientras la estatua de piedra los masacra uno a uno. Parece que hay una salida a este pérfido juego, pero ¿a qué precio?",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/50a0eb40c919b8efea01fd4799df08ff.jpe",
        releaseDate: "Enero 13, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "Es como un videojuego",
        duration: "24 min",
        description:
          "Para su sorpresa, Jin-Woo se despierta sano y salvo en el hospital. Al principio cree que los horripilantes sucesos que ha vivido son un sueño, pero las pantallas de estado no desaparecen y no parecen ser visibles para nadie más.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/c6adceca173ff32ae979af193a476fb2.jpe",
        releaseDate: "Enero 20, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "Tengo que hacerme más fuerte",
        duration: "24 min",
        description:
          "En un mundo donde portales misteriosos conectan con mazmorras llenas de monstruos, Sung Jin-Woo lucha por sobrevivir como el cazador más débil.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/78de61960488c9f16f960dae0b554eca.jpe",
        releaseDate: "Enero 27, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Un muy buen trato",
        duration: "24 min",
        description:
          "Cuando Jinwoo sale del hospital, las enfermeras se fijan en su buen estado físico. ¿Siempre tuvo tan buen cuerpo? Poco después, un grupo de Cazadores de rango C buscan un par de compañeros para rellenar y poder entrar a una mazmorra también C, así que como le ofrecen una buena cantidad, acepta.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/403416c5837765866f3b19ac27932777.jpe",
        releaseDate: "Febrero 3, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "Comienza la verdadera caza",
        duration: "24 min",
        description:
          "Jinwoo cae en la trampa que su nuevo equipo temporal le tiende y tiene que sobrevivir como puede, una vez más, ante un monstruo mucho más poderoso que él. A su lado está Jinho, a quien también han abandonado.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/4622fd0dd6f0072211526a8ae67f0c5c.jpe",
        releaseDate: "Febrero 10, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7,
        title: "Veamos hasta dónde puedo llegar",
        duration: "24 min",
        description:
          "Tras el incidente en la mazmorra de rango C, Jinwoo sigue con su vida como siempre, aunque su hermana no acaba de creer la gran evolución de su hermano.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/018425874ef4c1b18b32c26645d6c848.jpe",
        releaseDate: "Febrero 17, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 7.5,
        title: "Episodio especial",
        duration: "24 min",
        description: "Repasamos la historia hasta el momento.",
        img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/693c3c2259bf67d2afd151453ff15e1d.jpe",
        releaseDate: "Febrero 24, 2024",
        language: "Subtitulado",
        videoUrl: "frame/Solo-Leveling/T1/1.html.html",
      },
      {
        season: 1,
        number: 8,
        title: "Esto es frustrante",
        duration: "24 min",
        description:
          "Tras su última incursión en una mazmorra, Jinwoo se ha dado cuenta de su propia debilidad. Quiere subir de nivel lo antes posible, pero eso podrá hacerlo si consigue entrar en las mazmorras.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/ba4454c313d44737a3a72fc390bd2159.jpe",
        releaseDate: "Marzo 2, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 9,
        title: "Has estado ocultando tus habilidades",
        duration: "24 min",
        description:
          "El grupo de supervivientes de la mazmorra doble entra en la mazmorra junto a los presos condenados y Kang Taeshik, el cazador encargado de supervisar a los prisioneros. Sin embargo, lo que parecía un viaje normal a una mazmorra acaba siendo un río de sangre.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/08ade842ca3ae544ccc5e4f6a207b529.jpe",
        releaseDate: "Marzo 9, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 10,
        title: "¿Qué es esto, un pícnic?",
        duration: "24 min",
        description:
          "Jinwoo y Jinho preparan un grupo repleto de figurantes para entrar ellos solos a las mazmorras y conseguir dinero, pero esto hace que Tigre Blanco se fije en las posibles capacidades de Jinwoo y sospechen de que vivió un segundo despertar.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/9833d2909af5311139e79b32a44d9605.jpe",
        releaseDate: "Marzo 16, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 11,
        title: "Un caballero defendiendo un trono vacío",
        duration: "24 min",
        description:
          "Sung Jinwoo inicia la misión para cambiar de clase y se enfrenta a un enemigo formidable. Mientras, Jinho se reúne con su familia y otros cazadores visitan la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,width=320,height=180,fit=contain,quality=70/catalog/crunchyroll/66e3cabc8e0557f77c93c24178e7a5cd.jpe",
        releaseDate: "Marzo 23, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 1,
        number: 12,
        title: "Surge",
        duration: "24 min",
        description:
          "Mientras Jinwoo se enfrenta a sí mismo e intenta completar el cambio de clase, Choi Jong-in y los cazadores que lo acompañan descubren algo en la isla de Jeju.",
        img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/format=auto,fit=contain,width=320,height=180,quality=70/catalog/crunchyroll/cda77a98de7021522ebb5f0cc9bebd7d.jpe",
        releaseDate: "Marzo 30, 2024",
        language: "Sub | Dob",
        videoUrl: "frame/Solo-Leveling/T1/1.html",
      },
      {
        season: 2,
        number: 25,
        title: "Al siguiente objetivo",
        duration: "23 min",
        img: "https://img1.ak.crunchyroll.com/i/spire1/1a293b685a23d4f8fc4152912a7288f31690858883_main.jpg",
      },
      {
        season: 2,
        number: 24,
        title: "¿Eres el rey de los humanos?",
        duration: "23 min",
        img: "https://img1.ak.crunchyroll.com/i/spire4/e7887411c401319d67554559383679631689625399_main.jpg",
      },
    ],
  },
  {
    id: "pokemon-horizons",
    title: "Pokémon: Horizons",
    img: "https://cdn.jkdesu.com/assets/images/animes/image/pokemon-shinsaku-anime.jpg",
    heroImg:
      "https://occ-0-1472-3933.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABZkn668wtTIk2Wj95lXRnBdbtWHwlbHANeTm90WzC9sODu264-K_UlZ48VH57ZWCtksRr8vryMNLFYm7I9nlRB2Cqbl2qo-dpJmq.jpg?r=f75",
    logoImg:
      "https://upload.wikimedia.org/wikipedia/commons/e/e8/Pok%C3%A9mon_Horizons_The_Series_Logo.png",
    trailerUrl: "https://www.youtube.com/embed/_c_hMehCORQ",
    description:
      "Pocket Mosnters, Pokemon para abreviar. Las extrañas y misteriosas criaturas de este planeta se pueden ver en todas partes: en el cielo, en el mar, en el bosque y en la ciudad. Liko, una chica de Pardea con un misterioso colgante, y Roy, un chico de Kantou que sostiene una misteriosa bola monstruosa. Ambientada en el vasto mundo de Pokemon. ¡Comienzan las nuevas aventuras de Liko y Roy! ¿Qué encuentros les esperan y qué destino les aguarda? Esta es una historia sobre “encontrar” algo importante a través de la aventura.",
    genres: ["Acción", "Comedia", "Aventura", "Fantasía", "Infantil"],
    rating: 4.7,
    seasons: 1,
    episodesTotal: 99,
    status: "En Emisión",
    year: 2023,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 7)), // Hace 7 dias
    episodes: [
      {
        season: 1,
        number: 1,
        title: "del principio.",
        duration: "24m",
        description:
          "Liko, de la región de Paldea, llega a la Academia Índigo en Kanto, donde recibe a su primer compañero Pokémon, Sprigatito. Sin embargo, un grupo misterioso aparece buscando su enigmático colgante.",
        img: "image/Pokemon-Horizons/1.jpg",
        releaseDate: "14/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/1.html",
      },
      {
        season: 1,
        number: 2,
        title: "del principio, parte 2.",
        duration: "24m",
        description:
          "Liko es rescatada por los Tacleadas de Voltios, un grupo de aventureros. Friede y su Charizard se enfrentan a los Exploradores para proteger a Liko y su colgante.",
        img: "image/Pokemon-Horizons/2.jpg",
        releaseDate: "14/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/2.html",
      },
      {
        season: 1,
        number: 3,
        title: "con Sprigatito.",
        duration: "24m",
        description:
          "A bordo de la aeronave de los Tacleadas de Voltios, Sprigatito desaparece. Liko, con la ayuda de su nuevo amigo Roy, debe encontrar a su compañero antes de que los Exploradores ataquen de nuevo.",
        img: "image/Pokemon-Horizons/3.jpg",
        releaseDate: "21/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/3.html",
      },
      {
        season: 1,
        number: 4,
        title: "arrastrado por la marea.",
        duration: "24m",
        description:
          "Roy le muestra a Liko su base secreta. Mientras tanto, los Tacleadas de Voltios buscan a un Pokémon raro, Fuecoco, que ha sido visto en la isla. Roy sueña con convertirse en un Entrenador Pokémon.",
        img: "image/Pokemon-Horizons/4.jpg",
        releaseDate: "28/04/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/4.html",
      },
      {
        season: 1,
        number: 5,
        title: "Te  Fuecoco.",
        duration: "24m",
        description:
          "Fuecoco, atraído por el canto, se une a Roy. Juntos, se enfrentan a los Exploradores, y Roy demuestra su valentía como nuevo Entrenador Pokémon.",
        img: "image/Pokemon-Horizons/5.jpg",
        releaseDate: "05/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/5.html",
      },
      {
        season: 1,
        number: 6,
        title: "antigua.",
        duration: "24m",
        description:
          "El colgante de Liko revela un Pokémon misterioso que los protege. Siguiendo el consejo de la abuela de Liko, el grupo se dirige a Paldea para desentrañar el misterio de la Poké Ball antigua de Roy.",
        img: "image/Pokemon-Horizons/6.jpg",
        releaseDate: "12/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/6.html",
      },
      {
        season: 1,
        number: 7,
        title: "¡Entrenamiento  Capitán Pikachu.",
        duration: "24m",
        description:
          "Liko y Roy comienzan su entrenamiento especial con el Capitán Pikachu para fortalecer sus lazos con Sprigatito y Fuecoco y mejorar sus habilidades de combate.",
        img: "image/Pokemon-Horizons/7.jpg",
        releaseDate: "19/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/7.html",
      },
      {
        season: 1,
        number: 8,
        title: "de la puerta que no se abre.",
        duration: "24m",
        description:
          "La aeronave necesita reparaciones, y el grupo se detiene. Descubren una puerta misteriosa que no se abre, y Dot, la experta en tecnología del grupo, intenta resolver el enigma.",
        img: "image/Pokemon-Horizons/8.jpg",
        releaseDate: "26/05/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/8.html",
      },
      {
        season: 1,
        number: 9,
        title: "Paldea!.",
        duration: "24m",
        description:
          "Los Tacleadas de Voltios finalmente llegan a la región de Paldea. Liko está emocionada por regresar a casa, pero los peligros de los Exploradores aún los acechan.",
        img: "image/Pokemon-Horizons/9.jpg",
        releaseDate: "02/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/9.html",
      },
      {
        season: 1,
        number: 10,
        title: "Brassius.",
        duration: "24m",
        description:
          "En su búsqueda de información, Liko y Roy conocen a Nemona, una entrenadora de alto rango, y a Brassius, el líder de gimnasio de tipo Planta, quien parece tener una conexión con el Rayquaza negro.",
        img: "image/Pokemon-Horizons/10.jpg",
        releaseDate: "09/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/10.html",
      },
      {
        season: 1,
        number: 11,
        title: "El Bosque de Arboliva.",
        duration: "24m",
        description:
          "El grupo se adentra en el Bosque de Arboliva, donde se encuentran con un Arboliva gigante, uno de los seis héroes del antiguo aventurero Lucius, que parece estar herido.",
        img: "image/Pokemon-Horizons/11.jpg",
        releaseDate: "16/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/11.html",
      },
      {
        season: 1,
        number: 12,
        title: "El futuro que elijo.",
        duration: "24m",
        description:
          "Con el bosque en llamas, Liko y Sprigatito deben superar sus miedos para salvar al Arboliva gigante. El colgante de Liko vuelve a brillar, revelando su verdadero poder.",
        img: "image/Pokemon-Horizons/12.jpg",
        releaseDate: "23/06/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/12.html",
      },
      {
        season: 1,
        number: 13,
        title: "Un picnic repentino.",
        duration: "24m",
        description:
          "Después de la intensa batalla, el grupo decide tomar un descanso y hacer un picnic. Es un momento de calma para conocerse mejor y fortalecer sus lazos.",
        img: "https://image.tmdb.org/t/p/w300/aexpQXTfIcienaPGC4elDfFiTe8.jpg",
        releaseDate: "14/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/13.html",
      },
      {
        season: 1,
        number: 14,
        title: "¡Vuela! ¡¡Wattrel!!.",
        duration: "24m",
        description:
          "Un Wattrel que no puede volar le recuerda a Roy su propio pasado. Él y Fuecoco deciden ayudar al pequeño Pokémon a surcar los cielos.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-14.jpg",
        releaseDate: "21/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/14.html",
      },
      {
        season: 1,
        number: 15,
        title: "¡Alguien a quién no podemos ver! ¿Quién podrá ser?.",
        duration: "24m",
        description:
          "Algo o alguien invisible está causando travesuras en la aeronave. Dot y su Quaxly intentan descubrir al misterioso culpable.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-15.jpg",
        releaseDate: "28/07/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/15.html",
      },
      {
        season: 1,
        number: 16,
        title: "Mientras esté con Quaxly.",
        duration: "24m",
        description:
          "Se revela que el Pokémon invisible es un Polteageist. Liko ayuda a Dot a comprender mejor los sentimientos de su Quaxly para resolver el problema.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-16.jpg",
        releaseDate: "04/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/16.html",
      },
      {
        season: 1,
        number: 17,
        title: "¡Wattrel y Fuecoco: Entrenamiento secreto!.",
        duration: "24m",
        description:
          "Roy idea un entrenamiento secreto para que Wattrel y Fuecoco aprendan un nuevo movimiento combinado para impresionar a Friede.",
        img: "https://image.tmdb.org/t/p/w300/mbwNHNdQOBtaPfvocQOAvstNuxP.jpg",
        releaseDate: "11/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/17.html",
      },
      {
        season: 1,
        number: 18,
        title: "¡Vuela alto Pikachu, el cielo es el límite!.",
        duration: "24m",
        description:
          "El Capitán Pikachu muestra sus impresionantes habilidades de vuelo, inspirando a todo el equipo de los Tacleadas de Voltios.",
        img: "https://image.tmdb.org/t/p/w300/bK6nhaoHxuuqvp0TryDzyqswEVw.jpg",
        releaseDate: "18/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/18.html",
      },
      {
        season: 1,
        number: 19,
        title: "La verdad sobre Alcremie.",
        duration: "24m",
        description:
          "Murdock, el cocinero de la aeronave, está de mal humor. Liko y Roy investigan y descubren que el problema está relacionado con su Alcremie.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-19.webp",
        releaseDate: "25/08/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/19.html",
      },
      {
        season: 1,
        number: 20,
        title: "Batalla de entrenamiento con Kabu-san.",
        duration: "24m",
        description:
          "El grupo llega a la región de Galar y se encuentra con Kabu, el líder de gimnasio de tipo Fuego. Liko y Roy tienen una batalla de entrenamiento para probar su valía.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-20.jpg",
        releaseDate: "01/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/20.html",
      },
      {
        season: 1,
        number: 21,
        title: "¡La Hatenna que está sola!.",
        duration: "24m",
        description:
          "Liko encuentra una Hatenna solitaria que evita a las personas. Ella intenta ganarse la confianza del tímido Pokémon.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-21.webp",
        releaseDate: "08/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/21.html",
      },
      {
        season: 1,
        number: 22,
        title: "¡Choque en las minas de Galar!.",
        duration: "24m",
        description:
          "En las minas de Galar, los Tacleadas de Voltios se enfrentan nuevamente a los Exploradores, esta vez liderados por el astuto Spinel.",
        img: "https://image.tmdb.org/t/p/w300/mnVtj7XFhOLaGedViQNnQWjV1BK.jpg",
        releaseDate: "15/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/22.html",
      },
      {
        season: 1,
        number: 23,
        title: "¡El ardiente Moltres de Galar!.",
        duration: "24m",
        description:
          "Dentro de la mina, el grupo se encuentra con el legendario Moltres de Galar, otro de los seis héroes de Lucius, que está bajo un extraño control.",
        img: "https://image.tmdb.org/t/p/w300/aSqhLx2HlNDJ9oZuMyPddhAr0m3.jpg",
        releaseDate: "22/09/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/23.html",
      },
      {
        season: 1,
        number: 24,
        title: "Reunión en el antiguo castillo.",
        duration: "24m",
        description:
          "Siguiendo el rastro de la Poké Ball antigua, Liko visita a su abuela en un viejo castillo, donde se reencuentra con Diana y descubre más sobre Lucius.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-24.webp",
        releaseDate: "14/10/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/24.html",
      },
      {
        season: 1,
        number: 25,
        title: "¡Rivales en la noche oscura!.",
        duration: "24m",
        description:
          "Spinel de los Exploradores tiende una emboscada en el castillo. Liko y Roy deben proteger el colgante y enfrentarse a él y a su poderoso Umbreon.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-25.webp",
        releaseDate: "20/10/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/25.html",
      },
      {
        season: 1,
        number: 26,
        title: "La aventura de Terapagos.",
        duration: "24m",
        description:
          "El colgante finalmente se abre, revelando a un misterioso Pokémon tortuga. Diana lo identifica como Terapagos, comenzando una nueva etapa en la aventura.",
        img: "https://image.tmdb.org/t/p/w300/6YL02AlYxilPk8zfYk6lMk5sgp7.jpg",
        releaseDate: "07/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/26.html",
      },
      {
        season: 1,
        number: 27,
        title: "Mientras esté con mis amigos.",
        duration: "24m",
        description:
          "El grupo necesita reparar la aeronave. Para conseguir fondos, Liko, Roy y Dot deciden ayudar a un comerciante local con sus tareas.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-27.webp",
        releaseDate: "07/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/27.html",
      },
      {
        season: 1,
        number: 28,
        title: "Mientras esté con mis amigos.",
        duration: "24m",
        description:
          "La segunda parte del episodio 27. Liko, Roy y Dot continúan sus trabajos para ayudar a reparar el Valiente Asagi, fortaleciendo su amistad en el proceso.",
        img: "https://image.tmdb.org/t/p/w300/5jDep84tch9dmuHDwh8ImiM3Xsj.jpg",
        releaseDate: "11/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/28.html",
      },
      {
        season: 1,
        number: 29,
        title: "Orio y la artesana de Monster Ball.",
        duration: "24m",
        description:
          "Orio, la mecánica, visita a una artesana de Poké Balls para conseguir materiales. Liko y Roy la acompañan y aprenden sobre el antiguo arte de la fabricación de Poké Balls.",
        img: "https://image.tmdb.org/t/p/w300/5IO1vxBkf9VlZg7gPShjNhgZ9yn.jpg",
        releaseDate: "18/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/29.html",
      },
      {
        season: 1,
        number: 30,
        title: "¡¿El Pokémon misterioso que sorbe y aplasta?!.",
        duration: "24m",
        description:
          "Un Pokémon desconocido está causando problemas en la cocina al sorber la electricidad. El grupo debe identificar y detener a la criatura escurridiza.",
        img: "https://porygonsubs.com/image/episode/640/360/horizontes-pokemon-30.webp",
        releaseDate: "25/11/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/30.html",
      },
      {
        season: 1,
        number: 31,
        title: "La canción en la niebla.",
        duration: "24m",
        description:
          "Una espesa niebla rodea la aeronave y se escucha una canción misteriosa. La leyenda dice que es un Lapras, otro de los seis héroes de Lucius.",
        img: "https://image.tmdb.org/t/p/w300/daSHMLMsQ6lIwvGH8PPKXAhBywL.jpg",
        releaseDate: "02/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/31.html",
      },
      {
        season: 1,
        number: 32,
        title: "¡Los sentimientos de Lapras por sus amigos!.",
        duration: "24m",
        description:
          "El grupo descubre que el Lapras de Lucius protege a otros Pokémon heridos. Liko y Roy deben ganarse su confianza para poder ayudar.",
        img: "https://image.tmdb.org/t/p/w300/5dF3dIUsyenLPSyf1Qh50Ql3Z4A.jpg",
        releaseDate: "09/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/32.html",
      },
      {
        season: 1,
        number: 33,
        title: "El rugiente Rayquaza negro.",
        duration: "24m",
        description:
          "El legendario Rayquaza negro aparece. Amethio de los Exploradores también llega para desafiarlo, resultando en una batalla colosal que pone a todos en peligro.",
        img: "https://image.tmdb.org/t/p/w300/gn3PBYUbapyyObeOPfT745M8RQd.jpg",
        releaseDate: "16/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/33.html",
      },
      {
        season: 1,
        number: 34,
        title: "¡Cada quien por su camino!.",
        duration: "24m",
        description:
          "Tras la batalla con Rayquaza, el grupo se separa para entrenar individualmente y volverse más fuertes, prometiendo reunirse en el futuro.",
        img: "https://image.tmdb.org/t/p/w300/z9Yk1iym7SWeyJdE0zFOITQTTZH.jpg",
        releaseDate: "23/12/23",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/34.html",
      },
      {
        season: 1,
        number: 35,
        title: "Un dúo en el desierto: Friede y Cap.",
        duration: "24m",
        description:
          "Friede y el Capitán Pikachu se encuentran con una antigua rival en el desierto. Un flashback revela cómo se conocieron y formaron su fuerte vínculo.",
        img: "image/Pokemon-Horizons/35.jpg",
        releaseDate: "13/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/35.html",
      },
      {
        season: 1,
        number: 36,
        title: "Operación ¡Amistad Oinkologne!.",
        duration: "24m",
        description:
          "Roy intenta ayudar a un par de Oinkologne rivales a hacerse amigos, organizando una operación especial para que trabajen juntos.",
        img: "https://image.tmdb.org/t/p/w300/ks24qtUi9ncZxMOuHyKmWqoXO9r.jpg",
        releaseDate: "20/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/36.html",
      },
      {
        season: 1,
        number: 37,
        title: "¿Fuecoco se convierte en un chico malo?.",
        duration: "24m",
        description:
          "Fuecoco comienza a actuar de forma rebelde y desobediente. Roy debe entender qué le sucede a su amigo para recuperar su confianza.",
        img: "https://image.tmdb.org/t/p/w300/lyavl8OW1TSaaDdDjZKN4KkG4S2.jpg",
        releaseDate: "27/01/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/37.html",
      },
      {
        season: 1,
        number: 38,
        title: "¿Un SOS de Tandemaus?.",
        duration: "24m",
        description:
          "Liko y su Hatenna reciben una señal de socorro de un Tandemaus. Deben encontrar la fuente del problema y ayudar al pequeño Pokémon ratón.",
        img: "https://image.tmdb.org/t/p/w300/dTrFyERs2BVKN91Gnd9QuMZhpm4.jpg",
        releaseDate: "03/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/38.html",
      },
      {
        season: 1,
        number: 39,
        title: "¡Tinkatink y el martillo de sus obsesiones!.",
        duration: "24m",
        description:
          "Un Tinkatink está robando objetos metálicos para construir su martillo. Dot y su Quaxly intentan detenerlo y enseñarle una lección.",
        img: "https://image.tmdb.org/t/p/w300/ulElHyjCDbdMojmrH22XCrP1ylP.jpg",
        releaseDate: "10/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/39.html",
      },
      {
        season: 1,
        number: 40,
        title: "¿Adiós, Sprigatito?.",
        duration: "24m",
        description:
          "Liko se preocupa por el comportamiento distante de Sprigatito. Teme que su compañero quiera dejarla, y debe enfrentar sus inseguridades para fortalecer su vínculo.",
        img: "https://image.tmdb.org/t/p/w300/9f9fU2Bw6gGYaa2TMUWnDwPrrjv.jpg",
        releaseDate: "17/02/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/40.html",
      },
      {
        season: 1,
        number: 41,
        title: "¡Aparece la mamá intensa!.",
        duration: "24m",
        description:
          "La madre de Liko, Lucca, una influyente figura, visita la aeronave. Su presencia pone a Liko nerviosa, quien busca impresionar a su exigente madre.",
        img: "https://image.tmdb.org/t/p/w300/stzTiUQGXCEz2gdz8DbvpbWg40N.jpg",
        releaseDate: "02/03/24",
      },
      {
        season: 1,
        number: 42,
        title: "El futuro que elijo.",
        duration: "24m",
        description:
          "Una vez más, Liko se enfrenta a una decisión crucial sobre su futuro y el de sus amigos. Recordando sus aventuras, toma una resolución importante.",
        img: "https://image.tmdb.org/t/p/w300/6uQBd2GaMWiUO7SGgp0sHAf4La6.jpg",
        releaseDate: "09/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/42.html",
      },
      {
        season: 1,
        number: 43,
        title: "El desafio de los exploradores.",
        duration: "24m",
        description:
          "Los Exploradores lanzan un nuevo y audaz desafío a los Tacleadas de Voltios, con la intención de apoderarse de Terapagos de una vez por todas.",
        img: "https://image.tmdb.org/t/p/w300/8Ti8CEBFbYVDLpeazuzARcSobfe.jpg",
        releaseDate: "16/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/43.html",
      },
      {
        season: 1,
        number: 44,
        title: "¡El plan para capturar a Rayquaza!.",
        duration: "24m",
        description:
          "Los Exploradores revelan su elaborado plan para capturar al Rayquaza negro. Los Tacleadas de Voltios deben intervenir para proteger al Pokémon legendario.",
        img: "https://image.tmdb.org/t/p/w300/juuSqkbTpJIzUEGZvcown1Ghdbu.jpg",
        releaseDate: "23/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/44.html",
      },
      {
        season: 1,
        number: 45,
        title: "Muy, muy lejos.",
        duration: "24m",
        description:
          "La batalla final por Rayquaza y Terapagos alcanza su clímax. Liko y Roy deben usar todo lo que han aprendido para proteger a sus amigos y al mundo.",
        img: "https://image.tmdb.org/t/p/w300/5c6p8xmKfW2Tmt1Vgrp1d1Jyeoa.jpg",
        releaseDate: "30/03/24",
        language: "Sub | Dob",
        videoUrl: "frame/Pokemon-horizons/T1/45.html",
      },
      {
        season: 1,
        number: 46,
        title: "¡La emocionante Academia Naranja!.",
        duration: "24m",
        description:
          "Liko, Roy y Dot se inscriben en la Academia Naranja para un curso de entrenamiento especial sobre la Teracristalización, donde conocen nuevos amigos y rivales.",
        img: "https://image.tmdb.org/t/p/w300/hdy614vEE6EA5tIA9rtFgc47HAw.jpg",
        releaseDate: "13/04/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/46.html",
      },
      {
        season: 1,
        number: 47,
        title: "¡Liko y Floragato, con todo el corazón!.",
        duration: "24m",
        description:
          "Sprigatito evoluciona a Floragato. Liko debe aprender a sincronizarse con la nueva personalidad y estilo de lucha de su compañero.",
        img: "https://image.tmdb.org/t/p/w300/9yWglObQVD2iF4npwSCq6NRCjlK.jpg",
        releaseDate: "20/04/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/47.html",
      },
      {
        season: 1,
        number: 48,
        title: "¡Brilla! ¡El destello del fuego y el arte!.",
        duration: "24m",
        description:
          "Roy y Fuecoco tienen su primer desafío Teracristal contra Brassius. Deben combinar el arte y el poder del fuego para ganar.",
        img: "image/Pokemon-Horizons/48.jpg",
        releaseDate: "04/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/48.html",
      },
      {
        season: 1,
        number: 49,
        title: "Dot y Gurumin.",
        duration: "24m",
        description:
          "La identidad secreta de Dot como la streamer Gurumin está en riesgo cuando una fanática la desafía. Dot debe equilibrar su vida real y su alter ego.",
        img: "image/Pokemon-Horizons/49.jpg",
        releaseDate: "11/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/49.html",
      },
      {
        season: 1,
        number: 50,
        title: "¡Deslumbra, Teracristalización! ¡¡Baila, Baila, Quaxly!!.",
        duration: "24m",
        description:
          "Dot y Quaxly se enfrentan a un desafío de baile que requiere el poder de la Teracristalización. Quaxly evoluciona a Quaxwell.",
        img: "image/Pokemon-Horizons/50.jpg",
        releaseDate: "18/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/50.html",
      },
      {
        season: 1,
        number: 51,
        title: "¡¿Un Floragato espinoso?! El misterioso pilar de flores.",
        duration: "24m",
        description:
          "Floragato no puede controlar su nuevo poder, creando un pilar de espinas. Liko debe ayudarla a dominar su habilidad antes de que cause más problemas.",
        img: "image/Pokemon-Horizons/51.jpg",
        releaseDate: "25/05/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/51.html",
      },
      {
        season: 1,
        number: 52,
        title: "¡Wattrel, alerta de huracán!.",
        duration: "24m",
        description:
          "El Wattrel de Roy evoluciona a Kilowattrel y accidentalmente crea un pequeño huracán. Roy debe aprender a manejar el nuevo poder de su Pokémon.",
        img: "image/Pokemon-Horizons/52.jpg",
        releaseDate: "01/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/52.html",
      },
      {
        season: 1,
        number: 53,
        title: "Hatenna y el que no es de este mundo.",
        duration: "24m",
        description:
          "El grupo encuentra a un misterioso Pokémon que no parece de su mundo, y la Hatenna de Liko siente una conexión especial con él.",
        img: "image/Pokemon-Horizons/53.jpg",
        releaseDate: "08/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/53.html",
      },
      {
        season: 1,
        number: 54,
        title: "Bendición eterna.",
        duration: "24m",
        description:
          "Liko, Roy y Dot buscan un lugar legendario en Paldea que se dice que concede una bendición eterna, esperando que ayude a Terapagos.",
        img: "image/Pokemon-Horizons/54.jpg",
        releaseDate: "15/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/54.html",
      },
      {
        season: 1,
        number: 55,
        title: "¡Enfrentamiento! La Élite Cuatro de Paldea.",
        duration: "24m",
        description:
          "Liko y Roy tienen la oportunidad de luchar contra miembros de la Élite Cuatro de Paldea, poniendo a prueba sus nuevas habilidades Teracristal.",
        img: "image/Pokemon-Horizons/55.jpg",
        releaseDate: "22/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/55.html",
      },
      {
        season: 1,
        number: 56,
        title: "¡Liko VS Chili! Más allá de la batalla.",
        duration: "24m",
        description:
          "Liko se enfrenta a Chili, miembro de la Élite Cuatro. La batalla le enseña una valiosa lección que va más allá de ganar o perder.",
        img: "image/Pokemon-Horizons/56.jpg",
        releaseDate: "29/06/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/56.html",
      },
      {
        season: 1,
        number: 57,
        title: "Un Terapagos que no conocía.",
        duration: "24m",
        description:
          "Terapagos revela una nueva forma y habilidad desconocida, sorprendiendo a todos y atrayendo la atención no deseada de los Exploradores.",
        img: "image/Pokemon-Horizons/57.jpg",
        releaseDate: "06/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/57.html",
      },
      {
        season: 1,
        number: 58,
        title: "¡¿El Pokémon mascota es Kingambit?!.",
        duration: "24m",
        description:
          "El grupo se encuentra con un Kingambit que actúa como el jefe de una banda de Pawniard y Bisharp. Deben demostrar su fuerza para ganarse su respeto.",
        img: "image/Pokemon-Horizons/58.jpg",
        releaseDate: "13/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/58.html",
      },
      {
        season: 1,
        number: 59,
        title: "¡Baila, Quaxly! ¡¡El paso azul de Champuru!!.",
        duration: "24m",
        description:
          "Quaxwell evoluciona a Quaquaval y debe perfeccionar su paso de baile característico para dominar su movimiento 'Danza Acuática'.",
        img: "image/Pokemon-Horizons/59.jpg",
        releaseDate: "27/07/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/59.html",
      },
      {
        season: 1,
        number: 60,
        title: "¡Nuestra primera nevada! ¡Ho-ho-ge!!.",
        duration: "24m",
        description:
          "El grupo experimenta su primera nevada en el Monte Nappe. Fuecoco, un Pokémon de fuego, no está acostumbrado al frío y Roy debe encontrar una manera de mantenerlo caliente.",
        img: "image/Pokemon-Horizons/60.jpg",
        releaseDate: "10/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/60.html",
      },
      {
        season: 1,
        number: 61,
        title: "¡Resuena, alma mía! ¡El desafío de Rhyme!.",
        duration: "24m",
        description:
          "Liko se enfrenta a Rhyme, la líder de gimnasio de tipo Fantasma, en una batalla doble que también es una actuación de rap.",
        img: "image/Pokemon-Horizons/61.jpg",
        releaseDate: "17/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/61.html",
      },
      {
        season: 1,
        number: 62,
        title: "¡La canción de Fuecoco y yo!.",
        duration: "24m",
        description:
          "Fuecoco evoluciona a Crocalor y obtiene un nido de fuego en su cabeza. Roy debe aprender a cantar en sintonía con él para potenciar su movimiento 'Canto Ardiente'.",
        img: "image/Pokemon-Horizons/62.jpg",
        releaseDate: "24/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/62.html",
      },
      {
        season: 1,
        number: 63,
        title: "¡La batalla de hielo! ¡Grusha de los ojos fríos!.",
        duration: "24m",
        description:
          "Roy desafía a Grusha, el líder de gimnasio de tipo Hielo. Debe usar el calor de Crocalor y su ingenio para derretir la fría estrategia de Grusha.",
        img: "image/Pokemon-Horizons/63.jpg",
        releaseDate: "31/08/24",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/63.html",
      },
      {
        season: 1,
        number: 95,
        title: "¡Esfera Fuerte!.",
        duration: "24m",
        description:
          "Los Tacleadas de Voltios investigan un nuevo misterio relacionado con la energía Teracristal y descubren una extraña Esfera Fuerte que emite un poder inusual.",
        img: "https://image.tmdb.org/t/p/w300/o8c7XFzoYlGIHTWzHohzBXpEOjg.jpg",
        releaseDate: "10/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/95.html",
      },
      {
        season: 1,
        number: 96,
        title: "¡Colisión! La Banda Dragón Explosiva.",
        duration: "24m",
        description:
          "Una banda de entrenadores de tipo Dragón conocida como la 'Banda Dragón Explosiva' desafía a Roy. Es una batalla intensa para probar quién es el mejor entrenador de dragones.",
        img: "https://cdn.jkdesu.com/assets/images/animes/video/image_thumb/jkvideo_66edbe15461d3df54c8eaf3c998d74a4.jpg",
        releaseDate: "17/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/96.html",
      },
      {
        season: 1,
        number: 97,
        title: "¿La encantadora sonrisa del bromista Stunfisk?.",
        duration: "24m",
        description:
          "Un Stunfisk bromista está causando problemas al grupo con sus trampas eléctricas. Deben ser más astutos que el Pokémon para poder continuar su viaje.",
        img: "https://cdn.jkdesu.com/assets/images/animes/video/image_thumb/jkvideo_3cfdea3deff2a099b789026f47c841aa.jpg",
        releaseDate: "31/05/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/97.html",
      },
      {
        season: 1,
        number: 98,
        title: "¡Reencuentro en Pueblo Cercle!.",
        duration: "24m",
        description:
          "Liko, Roy y Friede llegan a Pueblo Cercle en la región de Paldea. Allí se reencuentran con Dot, quien está investigando un misterioso fenómeno relacionado con Pokémon que no pueden usar sus habilidades.",
        img: "https://image.tmdb.org/t/p/w300/vwCpEvwV4jGhjnWbdxKeYp2mbXV.jpg",
        releaseDate: "07/06/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/98.html",
      },
      {
        season: 1,
        number: 99,
        title: "¡Una Orio que no puede volar y...!.",
        duration: "24m",
        description:
          "Liko y Roy conocen a Orio, una ingeniera mecánica de los Tacleadas de Voltios. Descubren que Orio tiene un problema: ¡su Elekid no puede usar movimientos de tipo Eléctrico!",
        img: "https://image.tmdb.org/t/p/w300/2CxBqwCBj87Izt5lvqiAE4WLBHX.jpg",
        releaseDate: "14/06/25",
        language: "Subtitulado",
        videoUrl: "frame/Pokemon-horizons/T1/99.html",
      },
    ],
  },
  {
    id: "pokemon-viajes",
    title: "Pokémon: Viajes",
    img: "frame/Solo-Leveling/T1/1.html.jpg",
    description:
      "La historia final protagonizada por Satoshi y Pikachu para concluir Pokémon (2019). Aquí comienza la cuenta regresiva para despedirnos de Satoshi y Pikachu como protagonistas.",
    genres: ["Aventura"],
    rating: 4.8,
    seasons: 25,
    episodes: 1223,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "ranger-reject",
    title: "Ranger Reject (Sentai Daishikkaku)",
    img: "image/ranger-reject/p.webp",
    description:
      "Con su antiguo escondite y sus jefes aniquilados, los Dusters supervivientes llegan a un acuerdo secreto con el equipo Ranger para participar en el enfrentamiento dominical, uno en el que siempre serán derrotados. ¡Cansado de esta farsa, el Luchador D finalmente da un paso al frente para hacer un cambio de una vez por todas!.",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 2,
    episodes: 19,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 22)), // Hace 22 dias
  },
  {
    id: "dr-stone",
    title: "Dr. STONE",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    description:
      "Un día fatídico, toda la humanidad quedó petrificada por un destello de luz cegadora. Después de varios milenios, el estudiante Taiju despierta y se encuentra perdido en un mundo de estatuas.",
    genres: ["Aventura", "Ciencia Ficción", "Comedia"],
    rating: 4.8,
    seasons: 3,
    episodes: 57,
    status: "Finalizado",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 1)), // Ayer
  },
  {
    id: "one-piece",
    title: "One Piece",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/757bae5a21039bac6ebace5de9affcd8.jpe",
    description:
      "Monkey D. Luffy se niega a que nadie se interponga en su camino para convertirse en el rey de los piratas. ¡Una aventura épica por los mares en busca del tesoro legendario!",
    genres: ["Acción", "Aventura", "Comedia", "Fantasía"],
    rating: 4.9,
    seasons: 21,
    episodes: 1100,
    status: "En emisión",
    year: 1999,
    type: "TV",
    quality: "1080p",
    tags: ["agregado", "recomendado"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 2)), // Hace 2 dias
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/f356e33a59518a1a361e6123485c2d43.jpe",
    description:
      "Tanjiro Kamado, un joven de buen corazón, encuentra a su familia masacrada por un demonio. Para empeorar las cosas, su hermana menor, Nezuko, ha sido transformada en un demonio.",
    genres: ["Acción", "Fantasía", "Histórico"],
    rating: 4.9,
    seasons: 4,
    episodes: 55,
    status: "En emisión",
    year: 2019,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 5)), // Hace 5 dias
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    description:
      "Yuji Itadori se traga un talismán maldito para proteger a sus amigos y ahora comparte su cuerpo con un poderoso demonio. Se une a una sociedad secreta de Hechiceros Jujutsu para cazar maldiciones.",
    genres: ["Acción", "Fantasía", "Escolar"],
    rating: 4.8,
    seasons: 2,
    episodes: 47,
    status: "Finalizado",
    year: 2020,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 3)), // Hace 3 dias
  },
  {
    id: "spy-x-family",
    title: "SPY x FAMILY",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/6b53c5c9676c86f45c81f33775928d3c.jpe",
    description:
      "El maestro espía 'Twilight' debe formar una familia falsa para llevar a cabo una misión. Lo que no sabe es que la 'esposa' que elige es una asesina y la 'hija' es una telépata.",
    genres: ["Acción", "Comedia", "Slice of Life"],
    rating: 4.9,
    seasons: 2,
    episodes: 37,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "agregado", "doblaje"],
    dateAdded: new Date(), // Hoy
  },
  {
    id: "blue-lock",
    title: "Blue Lock",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=480,height=720/catalog/crunchyroll/b5621ff1277ed6ad1006b0c6f14900bb.jpg",
    description:
      "Tras una desastrosa derrota en el Mundial, 300 de los mejores delanteros de Japón son reunidos en una instalación similar a una prisión llamada 'Blue Lock' para crear al delantero más egoísta del mundo.",
    genres: ["Deportes", "Drama"],
    rating: 4.7,
    seasons: 1,
    episodes: 24,
    status: "Finalizado",
    year: 2022,
    type: "TV",
    quality: "1080p",
    tags: ["recomendado", "doblaje", "agregado"],
    dateAdded: new Date(new Date().setDate(new Date().getDate() - 38)), // Hace 38 dias
  },
];

export const newEpisodes = [
  {
    id: 1,
    title: "I've Been Killing Slimes For 300 Years",
    meta: "Episodio 5 • Sub | Dob",
    time: "14:00",
    img: "https://imgsrv.crunchyroll.com/cdn-cgi/image/fit=contain,format=auto,quality=85,width=1200,height=675/catalog/crunchyroll/fa62dd1fc7a9bc0b587f36f53bf572c1.jpg",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire1/b753dcccb08721820482a868353388f61618002633_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 5,
  },
  {
    id: 2,
    title: "Private Tutor to the Duke's Daughter",
    meta: "Episodio 1 • Subtitulado",
    time: "12:00",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/36181b3b55c6b841315842838423403a.jpe",
    hoverImg:
      "https://img1.ak.crunchyroll.com/i/spire2/d6c810e46c1f10255c27f31ab2c24c7e1720377038_main.jpg",
    url: "#",
    day: "hoy",
    episodeNum: 1,
  },
  {
    title: "Classic Stars",
    meta: "Episodio 13",
    time: "12:15",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/240x360/catalog/crunchyroll/d719910d5538e1b343a4155b1784d1a0.jpe",
    url: "#",
    day: "hoy",
  },
  {
    title: "Dr. STONE",
    meta: "Episodio 12 • Sub | Dob",
    time: "15:00",
    img: "https://a.storyblok.com/f/178900/960x1357/d42021c586/dr-stone-science-future-kv.jpeg/m/filters:quality(95)format(webp)",
    url: "#",
    day: "ayer",
  },
  {
    title: "Jujutsu Kaisen",
    meta: "Episodio 24 • Subtitulado",
    time: "18:30",
    img: "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/ebcd65fa9fb83580062e7052fa6ee5a5.jpe",
    url: "#",
    day: "ayer",
  },
];
